---
title: "Conclusión"
---

La diversidad de acercamientos desarrollada en este libro, permite ser utilizado para evaluar una gran diversidad de hipótesis y temas. Pero, sin duda lo más importante no son las técnicas matemáticas sino las preguntas que queremos responder. Las hipótesis que se presentan desde el punto de vista de conservación, ecológicas, de historia de vida y evolutivas, son solo ejemplos de preguntas que pueden ser respondidas con los modelos de dinámica poblacional. Gran parte del libro es dedicado a reconocer los métodos cuantitativos y sus limitaciones, esto se debe a que para hacer análisis de dinámica poblacional hay que entender todos los pasos y reconocer que en cualquier de estos casos, existen errores cuantitativos y de interpretaciones, que pudiesen invalidar el trabajo final. Los autores de este libro, reconocen que el estudio de la dinamica poblacional es holístico, permitiendo evaluar historias de vida compleja.

En esta sección presentamos algunas preguntas principales que pudiese ser investigadas en el futuro.

## Preguntas ecológica

-   Aunque la mayoría de las especies de orquídea tienen solamente un polinizador, para aquella que tienen múltiples especies de polinizadores, no esta claro si esto afecta la dinámica de sus poblaciones [@tremblay1992trends; @ackerman2025persistent]. En otra palabra ¿las especies que tienen múltiples polinizadores tienen una mayor consistencia poblacional al compararlas con las especies con un solo polinizador? y de ser el caso ¿cuales son los facores que lo están motivando? por ejemplo: ¿Cuando uno evalúa la diversidad de polínios sobre los polinizadores, esa diversidad pudiese tener repercusiones en la producciónde frutos, calidad de las semillas y esto a su vez pudiera verse reflejado en la tasas de fecundidad y sobrevivencia de las plantulas, lo que se esperaría afectara la dinámica de las poblaicones. Desafortunadamente se conoce muy poco sobre el efecto de la diversidad de padres sobre la calidad de las semillas [@tremblay1994var; @light1998factors]

-   Típicamente los modelos están basados en la cantidad de reclutamiento que se observa en el laboratorio, lo cual es una subestimación, ya que a dicho valor se le debiera incorporar la proporción de semillas que llegan a un micronicho apropiado para la germinación, la proporción de semillas que germinan bajo las condiciones microambientales en las que se desarrollen, la perdidas por herbivoría o por desecación, etc. No esta claro, si esta subestimación es relevante en la dinámica de las especies en ambiente naturales. La evaluación de las germinación de semillas en el campo: dado a su pequeño tamaño y la dificultad de detectar las semillas en el campo, asi como los protocormos es un reto que necesita ser explorado con profundidad. En general se conoce muy poco sobre la proporción de las semillas producidas y que germinan en el campo [@ackerman1996seedling; @wilcock2002pollination; @ehrlen2000dispersal; @batty2001constraints].

-   El efecto de la variables abióticas sobre la historia de vida de las plantas comienzan a ser investigado [@morris2020biotic], y el efecto sobre orquídeas es un tema que merece atención. Por ejemplo ¿Cuál es el efecto de los patrones de variación abiótica sobre la persistencia de las poblaciones y su dinámica a largo plazo?.

-   Los efectos bióticos tal como herbivoría, interacciones con polinizadores, interacción con árboles forofitos (en el caso de orquídeas epífitas), la diversidad de micorrizas en la raíz de las orquídeas, etc pudieran tener un efecto sobre  los parámetros de la modelos de proyección poblacional (PPM) , por lo que se necesita explorar a mayor profundidad dichos efectos.

-   Aunque los ecólogos que trabajan con orquídeas, reconocen que muchas especies de orquídea se multiplican por clonaje, aparte de los trabajos de *Cypripedium* [@garcia2010living] no es evidente su impacto sobre la persistencia y dinámica de estas poblaciones. Muchas otras especies de orquídeas tienen una historia de vida que incluye clonaje tal como *Epidendrum*, *Artorima* pero no se ha evaluado su impacto sobre la dinámica poblacional.

## Preguntas de historia de vida

-   Cual son diferencias y similitudes en la historia de vida de las orquídeas cuando se compara epífitas, terrestres, litófitas, templadas y tropicales?

-   Aunque hay poca diversidad de epifitas en áreas templadas, no son ausente, por ejemplo *Sarcochilus australis* es una epífita que se encuentra en Australia y Tasmania [@tremblay2006effect]. En general las orquídeas epifitas tienen una historia de vida diferente a las terrestres, pero no se ha evaluado si estas diferencias son relevantes para la dinámica poblacional.

-   La historia de vida de la especies terrestres en área templadas han sido bastante estudiando, pero en ambiente tropicales los estudios son escasos. Los que hemos encontrado son *Oeceoclades maculata* [@riveron2019spatio], *Phaius australis* [@simmons2016Viability] y *Spathoglottis plicata* [@falcon2017quantifying]. Debido que el ambiente tropical es menos variable en temperatura, cual efecto si algunos tiene sobre la historia de vida de las orquídeas terrestres tropical comparado a las especies templadas.

## Preguntas evolutivas

-   La historia de vida de los diferentes grupos de orquídea han influenciado la diversidad taxonómica?

-   Cual es el impacto de reproducción por clonaje sobre la dinámica poblacional y especialmente sobre los procesos evolutivos

-   ¿Cuál es la relación de la diversidad micorrízica, el ciclo de vida y la adecuación evolutiva? En otras palabras, ¿individuos con mayor diversidad micorrízica tienen una mayor adecuación evolutiva que individuos con menos diversidad hongos micorrízicos? O ¿los que tienen un simbionte específico tienen una mayor adecuación evolutiva, influenciando la edad a la primera reproducción o el esfuerzo reproductivo?
