# Capitulos Asignados

#### Librerías de R requeridas para el siguiente módulo

```{r, Asign_1, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)

```


## Procesos de cumplimiento y revisión interna

Aquí las asignaciones de los capitulas:

-   Favor indicar los errores y correcciones necesarias.

```{r, Asign_2, echo=FALSE}
Capitulos=tribble(~"Número del Capítulo", ~"Título del Capítulo", ~"Autor(es)", ~"Estatus", ~"Revisor(es)",~"Próximo revisor (fecha de espera)", ~"Fecha revisada",
                  "1", "Introducción", "TODOS", "En revisión", "1. RLT, 2. Elaine,  3. Tupac", " ", "1. Sept 14, 2024, 2. Feb 12, 2025, 3, 24/1/25  ",
                  "2", "Qué es el análisis de dinámica poblacional", "TODOS", "En revisión", "1. Ernesto, 2. RLT, 3. Tupac","","1. Feb 11, 2025, 2. Feb 13, 2025, 3. Feb 18, 2025 ",
                  "3", "Qué es un diagrama de ciclo de vida", "RLT", "Terminado", "1. RLT, 2. Mariana","Mariana, 14 de febrero","1. Sept 14, 2024",
                  "4", "Como recopilar datos en el campo", "Aucencia, Mariana, RLT", "En Proceso", "1. RLT, 2. RLT, 3. Mariana","","Sept 14, 2024, Jan 19, 2025, May 1 2025",
                  "5", "Como calcular transiciones para la matriz de lefkovitch", "Aucencia, Ernesto, Elaine", "Falta incluir la matrix de clonaje  ", "","","",
                  "6", "Como calcular fecundidad", "Aucencia y RLT", "?", "?","","14 de febrero",
                  "7", "Matrix matA=matU+matF+matC", "RLT", "Terminado", "1. RLT, 2. Demetria, 3. RLT","","1. RLT, 2. Demetria, 3. RLT",
                  "8", "Métodos bayesianos para estimar parámetros", "RLT", "Terminado", "1. RLT, 2. RLT","1. Paola, 25 de marzo","Sept 15, 2024, Oct 8, 2024",
                  "9", "Crecimiento poblacional", "Tamara y Mariana", "Terminado", "1. RLT","Adriana, 14 de febrero","1. 2025_01_18",
                  "10", "Estimación de parametros", "Mariana y Paola", "No terminado", "","","",
                  "11", "Elasticidad", "Demetria, Ernesto y Elaine", "No Terminado", "","Tupac","",
                  "12", "Dinamica de transición", "Mariana y Paola", "No Terminado", "","","",
                  "13", "Funciones de transferencia", "Mariana y Paola", "No Terminado", "","","",
                  "14", "Experimento de Respuesta de Tabla de Vida", "Adriana and Demetria", "Terminado", "","1. Adriana, 14 de febrero","",
                  "15", "Variación Temporal y Espacial", "RLT", "Terminado", "1. RLT","","1. 2024-09-30",
                  "16","El uso de matrices para estudios evolutivos", "Roberto Salguero Gomez", "?", "?","mensaje enviado 20/1/25","",
                  "17", "Breve Historia de la dinamica de población en orquídea", "RLT y ?", "Terminado", "1. RLT ","Mariana, 14 de febrero","1. Oct 1, 2024",
                  "18", "Carl Olaf Tamm", "RLT", "Terminado", "","","2025-05-05 Tupac",
                  "19", "Compadre", "RLT, Diana y Roberto", "Terminado", "1. RLT","mensaje enviado a Roberto? 20/1/25","1. Jan 20, 2025",
                  "20", "Un protocolo para informar sobre modelos discreto de estructura de población", "Gascoine et al.", "Terminado", "1.   RLT, 2. Roberto","","",
                  "21", "Impacto de datos sin sentido biológico", "RLT", "Terminado", "1. RLT, 2. Demetria, 3. Tupac","","1. 26-12-24, 2. 09-02-25, 3. 14-02-25",
                  "22", "Dracula chimaera", "Nhora, Andres y Anne", "No Terminado", "","","",
                  "Appendice A", "Lista de orquídea con análisis de matriz", "Compilado por RLT y ?", "No terminado", "","","",
                  "Appendice B", "Hojas de datos en el campo", "RLT", "Terminado", "","",""
                  
                  
          )


library(gt)

gt(Capitulos)
```


## Revisados por el Editor Externos

```{r, Asign_3, echo=FALSE}

Revisor_ext=tribble(~Núm_Capitulo, ~Titulo, ~Fecha_Revisado,
                    "Index", "Index", "No Terminado",
                    "1", "Introducción", "2025_02_18, No Terminado, en Revision por Tamara",
                  "2", "Qué es el análisis de dinámica poblacional", "Terminado",
                  "3", "Qué es un diagrama de ciclo de vida", "Terminado",
                  "4", "Como recopilar datos en el campo", "Terminado",
                  "5", "Como calcular transiciones para la matriz de lefkovitch", "Terminado",
                  "6", "Como calcular fecundidad", "Terminado",
                  "7", "Matrix matA=matU+matF+matC", "Terminado",
                  "8", "Métodos bayesianos para estimar parámetros", "Terminado, procesos de revision por Maria-Eglée Pérez y Paola Portillo",
                  "9", "Crecimiento poblacional", "Terminado",
                  "10", "Estimación de parametros", "No Terminado",
                  "11", "Elasticidad", "2025_06_06- Procesos de revision por Tupac",
                  "12", "Dinamica de transición", "No Terminado",
                  "13", "Funciones de transferencia", "No Terminado",
                  "14", "Experimento de Respuesta de Tabla de Vida", "No Terminado",
                  "15", "Variación Temporal y Espacial", "Terminado",
                  "16", "El uso de matrices para estudios evolutivos","No Terminado",
                  "17",  "Breve Historia de la dinamica de población en orquídea"," Terminado",
                  "18",  "Carl Olaf Tamm","2025_06_05, Revisado por Tupac",
                  "19",  "Compadre","Terminado",
                  "20",  "Un protocolo para informar sobre modelos discreto de estructura de población","Ya listo, Revisado por Roberto Salguero Gomez",
                  "21",  "Impacto de datos sin sentido biológico","2025_03_21, Revisado por Tupac",
                  "22",  "Dracula chimaera","No Terminado",
                  "23", "Conclusion", "No Terminado"
          )


gt(Revisor_ext)
```


