
project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Diagnostico Poblacional"
  # description: "Homepage for STA 210 - Regression Analysis at Duke University, Spring 2022."
  # site-url: "https://sta210-s22.github.io/website/"

 # repo-url: https://github.com/sta210-s22/website
 # repo-actions: [edit, issue]

  open-graph: true

#  twitter-card:
#    creator: "@minebocek"
#    image: "images/twitter-card.png"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Raymond L. Tremblay"
    background: "#D9E3E4"


  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center


    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Capítulos"
        contents:
        - href: index.qmd
          text: Home
        - href: 102-Intro.qmd
          text: Introducción
        - href: 103-Ciclos_de_Vida.qmd
          text: "Ciclos de Vida"
        - href: 104-Recopilacion_datos_en_el_campo.qmd
          text: "Recopilación de datos en el campo"
        - href: 105-Transiciones.qmd
          text: "Calcular transiciones"
        - href: 106-calcular_fecundidad.qmd
          text: "Calcular fecundidad"
        - href: 107-matU_matF_matC.qmd
          text: "Suma de matrices"
        - href: 108-Bayesian_PPM.qmd
          text: "Estimados bayesianos de PPM"
        - href: 109-Crecimiento_poblacional.qmd
          text: "Crecimiento poblacional"
        - href: 110-Indices.qmd
          text: "Índices demográficos"

bibliography: book.bib


format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true


editor: visual

