project:
  type: book
  output-dir: docs
  resources:
    - header.tex
    - google2352045df3d1e270.html
    - theme.scss
    - theme-dark.scss
    - images
    - favicon
book:
  title: Introducción a la Dinámica Poblacional de Orquídeas
  description: Dinámica Poblacional de Orquídeas.
  site-url: 'https://raymondltremblay.github.io/Dinamica_Poblacional/'
  repo-url: 'https://github.com/raymondltremblay/Dinamica_Poblacional'
  repo-actions:
    - edit
    - issue
  favicon: favicon/Orchid_purple.png
  chapters:
    - index.qmd
    - 102-Intro.qmd
    - 103-Ciclos_de_Vida.qmd
    - 104-Recopilacion_datos_en_el_campo.qmd
    - 105-Transiciones.qmd
    - 106-calcular_fecundidad.qmd
    - 107-matU_matF_matC.qmd
    - 108-Bayesian_PPM.qmd
    - 109-Crecimiento_poblacional.qmd
    - 110-Propriedades.qmd
    - 111-Elasticidad.qmd
    - 112-Dinamica_de_Transiciones.qmd
    - 113-Funciones_de_Transferencia.qmd
    - 114-LTRE.qmd
    - 115-Metodos_de_simulaciones.qmd
    - 119-COMPADRE_ORCHIDS.qmd
    - 120-Rage_orquideas.qmd
    - 121-Traduccion_protocolo_informacion.qmd
    - 122-Impacto_de_Datos_sin_Sentido.qmd
    - 123-Conclusion.qmd
    - part: Historia
      chapters:
        - 117_Historia_breve.qmd
        - 118-Carl_Olaf_Tamm.qmd
    - part: Apéndices
      chapters:
        - Appendix_A_Species_List.qmd
        - Appendix_B_Hoja_de_datos.qmd
        - Appendix_C_Datos.qmd
        - Agradecimientos.qmd
filters:
  - auto-functions.lua

bibliography: book.bib
csl: peerj.csl
format:
  html:
    theme:
      light:
        - cosmo
        - theme.scss
      dark:
        - cosmo
        - theme-dark.scss
    mainfont: Atkinson Hyperlegible
    toc: true
    toc-depth: 3
    code-copy: true
    code-fold: true
    math: mathjax
  pdf:
    pdf-engine: xelatex
    documentclass: book
    toc: true
    number-sections: true
    papersize: letter
    geometry: margin=1in
    fontsize: 12pt
    colorlinks: true
    include-in-header: header.tex

execute:
  warning: false
  message: false
  error: false

lang: es
editor: visual
