

project:
  type: website
  output-dir: docs

filters:
  - _extensions/mcanouil/iconify/iconify.lua # This line is critical!

website:
  page-navigation: true
  title: "Diagnostico Poblacional"
  # description: "Pagina principal: Dinámica poblacional."
  #site-url: "https://raymondltremblay.github.io/Dinamica_Poblacional/"

 # repo-url: https://raymondltremblay.github.io/Dinamica_Poblacional/
 # repo-actions: [edit, issue]

  open-graph: true

  #- icon: Bluesky_Logo.svg.png
    #href: https://raymondltremblay.github.io/Dinamica_Poblacional/
    #href: https//bsky.app/bluesky.social/@raymondltremblay

#  twitter-card:
#    creator: "@minebocek"
#    image: "images/twitter-card.png"

  page-footer:
    right: "Esta página fue creado ❤️ y [Quarto](https://quarto.org/)."
    left: "&copy; Diagnostico Poblacional; Copyright 2025, Raymond L. Tremblay"
    background: "#D9E3E4"


  sidebar:
    background: "#D9E3E4"
    logo: "images/MPP_Hex.jpeg"
    pinned: true
    align: center
    tools:
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/ # REPLACE with your Bluesky profile URL
        aria-label: "Bluesky Profile" # Important for accessibility
      - icon: github
        href: https://raymondltremblay.github.io/Dinamica_Poblacional
        text: "Analitica Fundación"
     # - icon: fa brands bluesky # Font Awesome Bluesky Install this.  <<install.packages("fontawesome")>>
       # href: https://bsky.app/
        # Bluesky icon using quarto-iconify shortcode




    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Capítulos"
        contents:
        - href: index.qmd
          text: Home
        - href: 102-Intro.qmd
          text: Introducción
        - href: 103-Ciclos_de_Vida.qmd
          text: "Ciclos de Vida"
        - href: 104-Recopilacion_datos_en_el_campo.qmd
          text: "Recopilación de datos en el campo"
        - href: 105-Transiciones.qmd
          text: "Calcular transiciones"
        - href: 106-calcular_fecundidad.qmd
          text: "Calcular fecundidad"
        - href: 107-matU_matF_matC.qmd
          text: "Suma de matrices"
        - href: 108-Bayesian_PPM.qmd
          text: "Estimados bayesianos de PPM"
        - href: 109-Crecimiento_poblacional.qmd
          text: "Crecimiento poblacional"
        - href: 110-Indices.qmd
          text: "Índices demográficos"
        - href: 111-Elasticidad.qmd
          text: "Elasticidad"
        - href: 112-Dinamica_de_Transiciones.qmd
          text: "Dinámica de Transiciones"
        - href: 113-Funciones_de_Transferencia.qmd
          text: "Funciones de Transferencia"
        - href: 114-LTRE.qmd
          text: "Experimento de Respuesta de Tabla de Vida"
        - href: 115-Metodos_de_simulaciones.qmd
          text: "Método de Simulaciones"
        - href: 116-Estudio_evolutivo.qmd
          text: "Estudios evolutivos"
        - href: 119-COMPADRE_ORCHIDS.qmd
          text: "COMPADRE y Orquídeas"
        - href: 120-Traduccion_protocolo_informacion.qmd
          text: "Traducción del protocolo de información"
        - href: 121-Impacto_de_Datos_sin_Sentido.qmd
          text: "Impacto de Datos sin Sentido Biológico"
        - href: 122-Conclusion.qmd
          text: "Conclusión"


      - section: "Historia"
        contents:
        - href: 117_Historia_breve.qmd
          text: "Historia breve de la demografía en orquídeas"
        - href: 118-Carl_Olaf_Tamm.qmd
          text: "Carl Olaf Tamm"

      - section: "Apéndices"
        contents:
        - href: Appendix_A_Species_List.qmd
          text: "Lista de Especies de Orquídeas en COMPADRE"
        - href: Appendix_B_Hoja_de_datos.qmd
          text: "Hoja de datos"
        - href: Appendix_C_Datos.qmd
          text: "Datos"
        - href: Agradecimientos.qmd
          text: "Agradecimientos"
        - href: 132_Capitulos_Asignados.qmd
          text: "Capítulos Asignados"

bibliography: book.bib
  # - grateful-refs.bib
  # - ftExtra.bib # in APPENDIX file
csl: peerj.csl


format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools:
      source: true
      toggle: true
      caption: Codes
  #pdf:
 #   toc: true
  #  toc-depth: 2
 #   number-sections: true
 #   code-overflow: wrap
 #   fig_caption: true
 #   latex-engine: xelatex
 #   documentclass: article
 #   keep-tex: true



editor: visual
