---
title: "Agradecimiento"
---

#### Librerías de R requeridas para el siguiente módulo

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
#library(gt)
library(flextable)
library(ftExtra)

```

Aprecio por compartir fotos

```{r, echo=FALSE, message=FALSE, warning=FALSE}
Fotos=tribble(~"Origen de las Fotos", ~Especie, ~ Dirección,
              "Hans Jacquemyn", "*Orchis purpurea*", "Leuven Plant Institute, KU Leuven, Leuven, Belgium",
              "Giuseppe Pellegrino", "*Serapias cordigera*", "Ecology and Earth Sciences, University of
Calabria, Rende, CS, Italy",
              "Mitch McClaran", "*Spiranthes delistecens*", "Professor of Range Management, School of Natural Resources and the Environment, Director for Research, Santa Rita Experimental Range https://santarita.arizona.edu/, College of Agriculture, Life, and Environmental Sciences, University of Arizona",
"Hong Liu", "*Trichocentrum undulatum*", "Department of Earth and Environment, Florida International University, Westchester, FL 33199, USA")


```



```{r, message=FALSE, warning=FALSE}
Fotos_out=Fotos %>%
  flextable() %>%
  theme_zebra() %>%
  theme_box() |> 
  colformat_md() %>% 
  set_table_properties(layout = "autofit")



Fotos_out


```

Aprecio por revisar capitulos

```{r, echo=FALSE, message=FALSE, warning=FALSE}

Revisores=tribble(~"Nombre", ~"Institución",
              "Joel Tupac", "",
              "Maria Eglée Pérez", "Departamento de Matematica, Universidad de Puerto Rico"
              )


Revisores
```




Aprecio por entrar datos en COMPADRE

```{r}
Benevolos=tribble(~"Nombre", ~"Institución",
              "Javielise Donato", "Universidad de Puerto Rico-Humacao, Puerto Rico",
              "Diana C. Molina Ozuma", "Colegio de la Frontera Sur, ECOSUR, México",
              "Nayliz M. Ortiz Ortiz", "Universidad de Puerto Rico-Humacao, Puerto Rico",
              "Gabriela Torres Torres", "Universidad del Valle, Colombia")

Benevolos
```

