---
title: "Diagnostico Poblacional: un acercamiento práctico"
author:
- name: Raymond L. Tremblay
  affiliation: Universidad de Puerto Rico, Recinto de Río Piedras, Departamento de
    Biología, San Juan, Puerto Rico, Universidad de Puerto Rico, Recinto de Humacao,
    Departamento de Biología, San Juan, Puerto Rico. ANALITICA Fundación, Inc. Caguas,
    Puerto Rico
- name: Aucencia Emeterio Lara
  affiliation: Colegio de la Frontera Sur, ECOSUR, México
- name: Elaine González
  affiliation: Orquídeario Soroa, Universidad de Pinar del Río, Apdo. postal No. 5
    Candelaria, Pinar del Río, Cuba
- name: "Mariana Hernández-Apolinar"
  affiliation: Universidad Nacional Autónoma de México, Facultad de Ciencias, México
- name: Demetria Mondragón
  affiliation: Instituto Politécnico Nacional, Centro Interdisciplinario de Investigación y Desarrollo Integral Regional Oaxaca, México
- name: Ernesto Mujíca Benitez
  affiliation: Orquídeario Soroa, Universidad de Pinar del Río, Apdo. postal No. 5
    Candelaria, Pinar del Río, Cuba
- name: Paola Portillo Tzompa
  affiliation: Universidad Nacional Autónoma de México, Facultad de Ciencias, México
- name: Roberto Salguero Gómez
  affiliation: "Laboratory of Evolutionary Biodemography Laboratory, Max Planck Institute
    for Demographic Research, Konrad-Zuse-Straße 1, Rostock DE-18057, Germany; ARC
    Centre of Excellence for Environmental Decisions, School of Biological Sciences,
    The University of Queensland, Goddard building 8, St. Lucia, Qld 4072, Australia;"
- name: Adriana Ramírez Martínez
  affiliation: "Instituto Politécnico Nacional, Centro Interdisciplinario de Investigación y Desarrollo Integral Regional Oaxaca, México"
- name: Tamara Ticktin
  affiliation: Department of Botany, University of Hawaii at Manoa, 3190 Maile Way,
    Honolulu, HI 96822, USA.
date: "`r Sys.Date()`"
#output: 
#  bookdown::html_document2: default

documentclass: book
bibliography:
- book.bib
- packages.bib
# - grateful-refs.bib
description: |
  Este libro digital es una introdución al estudio de la Dinámica Poblacional con ejemplos de orquídeas. Los capítulos están organizado de lo más básico a más complejo en la recolección de datos, análisis y interpretación de los resultados. Incluyendo acercamientos que fueron desarrollados más reciente para el análisis de datos de dinámica poblacional. Los capítulos de **Métodos Bayesiano de calcular las transiciones y fecundidad** y **Un protocolo para informar sobre modelos discreto de estructura de población** son especialmente importante para reducir los errores de cálculos de los parámetros, interpretación y divulgación de los trabajos. El capítulo de **Impacto de datos sin sentidos biológico** es *PRIMORDIAL* para los investigadores que trabajan con datos de dinámica poblacional y debería ser un capítulo donde uno regrese continualmente para evaluar la calidad de los análisis y interpretaciones. En otra palabra si los datos no tiene sentido biológico y matemático los resultados no sirven.  En adición se presenta múltiples ejemplos de datos sin sentido y como estos datos pueden impactar los resultados de los análisis de forma negativa. Al final del libro hay una pequeña introducción a la historía de la dinámica poblacional usando orquídea.  
  
Fecha de actualización: "2025-05-30"
---

------------------------------------------------------------------------

# Diagnostico Poblacional: Un acercamiento práctico

El estudio de la Dinámica Poblacional tiene como objetivo desarrollar conocimientos sobre los patrones y procesos intra-específica y variables inter-específicos que impacta en el crecimiento de una especie en particular. Tradicionalmente muchos de los trabajos de dinámica poblacional se enfocan en los estudios intra-específicos, fomentando una perspectiva que las especies no inter-actúan con su ambiente abiótico o con las especies en su entorno ecológico. Como toda las áreas de la ecología el desarrollo de los conceptos tienden a ser simplista al principio y con el tiempo se van complicando de forma conceptual y metodológicos. Para entender los procesos dinámicos de cualquier especie cuando se comienza a estudiar uno debería comenzar por modelos simples y con el tiempo ir complicando los modelos para entender los procesos más complejos y evaluar si realmente complicando los modelos se puede explicar mejor los procesos y patrones. Este libro comienza por explicar las herramientas, conceptos y métodos más básicos en la dinámica poblacional enfatizando los supuestos y la limitaciones en el uso de cada indice y sus acercamientos. Al final del libro se enfatiza en múltiples puntos que el investigador debería considerar en el momento de hacer un análisis de dinámica poblacional para reducir los sesgos y errores en los análisis.

## Objetivo del libro:

Este libro es orientado a dos grupos de personas: Para los estudiantes de pre-grado y posgrado que están interesados en aprender sobre la dinámica poblacional y para los investigadores que desean tener una guía de los conceptos y algunos métodos tradicionales y más actuales sobre la dinámica poblacional. En cada capítulo se presentará una introducción a los conceptos y métodos así como ejemplos prácticos de como aplicar estos conceptos y métodos usando la matemática más básica y su representación de forma biológica. En cada caso se ampliará con métodos y funciones disponible en varios paquetes de **R** para facilitar el análisis. La gran mayoría de los ejemplos matemáticos básicos se presentarán en **R**, y algunos en **MS Excel**. Al final se debería tener una apreciación de la diversidad de metodologías y conceptos en la dinámica poblacional y como se puede aplicar a sus estudios para contestar varios tipos de preguntas: sobre la ecología, la conservación y la evolución. Un esfuerzo de recopilar referencias de la literatura de la dinámica poblacional de las orquídeas y otros organismos (tanto animales como otro grupos de plantas) se ha hecho para que el lector pueda tener una idea de los estudios que se han hecho. Se espera que la diversidad de ejemplos puede dar una apreciación holística de la diversidad de acercamiento, fortalezas y retos.

## Estructura del libro

El libro se divide en **xx** capítulos. Estos capítulos están organizados para que el lector pueda seguir el proceso de recolección de datos, análisis y interpretación de los resultados. Incluyendo acercamientos que fueron desarrollados más reciente para el análisis de datos de dinámica poblacional. Los capítulos de **Métodos Bayesiano de calcular las transiciones y fecundidad** y **Un protocolo para informar sobre modelos discreto de estructura de población** son especialmente importante para reducir los errores de cálculos de los parámetros y divulgación de los trabajos.

1.  **Ciclo de vida de una especie**:

El primer capítulo presenta un concepto fundamental en la dinámica poblacional, el ciclo de vida. Cada especie tiene un ciclo de vida **REAL**, donde el investigador siempre debería tratar de replicar en la recolección de datos incluyendo información para cada etapa/edad de la vida de la especie. El ciclo de vida REAL es la base para entender los procesos de la dinámica poblacional. Noto aquí que entre el ciclo de vida REAL de una especie y la capacidad de recolección de datos sobre el mismo hay una brecha que el investigador debería tratar de cerrar. Un ejemplo extremo, recientemente acaban de descubrir un cadáver de una especie de ballena en Nueva Zelanda, que se llama “Spade tooth whale” donde se ha encontrado desde su descripción (1874) solamente 6 individuos. Sin duda hacer un estudio considerando el ciclo de vida de esta especie sería un reto. Cualquier especie que se estudie con tan pocos datos es un dificil, y múltiples supuestos del ciclo de vida de la especie tendrían que ser incluidos. Lo más importante es reconocer lo que es un supuesto (y por consecuencia una hipótesis) y lo que es un hecho o sea la realidad.

En las orquídeas, hay múltiples etapas del ciclo de vida, las etapas de semillas, germinación (colonización de semillas por un hongo apropiado para su germinación en el campo) y plántulas son etapas críticas en el ciclo de vida de las especies, pero son etapas difíciles para recolectar datos en el campo. Estas etapas son decisivas para entender la dinámica poblacional de las orquídeas, pero desafortunadamente todavía se desconocemos mucho sobre estas etapas en el campo, así como su variación en los procesos y patrones. Enfatizo el hecho de que son procesos en el hábitat natural, mucho de lo que se conoce es de estudios en laboratorio, que pudiese ser procesos y patrones sesgados.

En este capítulo se abordan varios aspectos del ciclo de vida de una especie y como se puede categorizar de forma práctica para la recolección de datos y entender los procesos de la dinámica poblacional para reconocer los supuestos y limitaciones en la interpretación de lo que es el ciclo de vida de la orquídea con los datos versus el ciclo de vida real de la especie.

2.  **Recolección de datos**:

En este capítulo se explica la recolección de datos en el campo, los métodos de muestreo, marcar, identificar y monitorear en el tiempo los individuos. Enfatizamos tres tipos de recolección de datos basado en su hábitat de crecimiento, las cuales pueden ser: epífitas, terrestres, y terrestres con latencia. Para ayudar en la compresión de los métodos de muestreo se presentará ejemplos de la literatura o experiencia de los autores. Se presenta múltiples métodos para hacer estudios de marca y recaptura en orquídeas y se sugiere múltiples sistemas de marca para reducir los errores de confusión en identificar individuos entre poblaciones y periodo de muestreo.

3.  **Transiciones de etapa/edad**:

El tercer capítulo se representa los cálculos de las transiciones de una etapa/edad de un muestreo a otro. Se comienza con los análisis que se pueden hacer a mano, y después se presentará como hacerlo en R. En este capítulo se presenta los métodos de calcular de forma simple y se discute algunos los supuestos y limitaciones. Estos métodos tradicional son especialmente práctico para poblaciones grandes con tamaño de muestra grande en todas las etapas o grupo de edad. Cuando los tamaños de muestra son pequeñas o la probabilidad de una transición es rara vea el capítulo de métodos Bayesianos para calcular las transiciones.

4.  **Calcular la fecundidad**:

Este capítulo se explica como calcular la fecundidad de una especie. El capítulo se enfoca en tratar de que los investigadores reconozcan que los indices de fecundidad tienen que estar relacionados con las etapas de vida de la especie que se esta modelando. En otra palabra si la primera etapa del ciclo de vida son plántulas, la fecundidad debería ser relacionada con la producción de semillas que se convierte en plántulas. En este tópico se presentará los métodos de calcular de forma simple y se discute algunos los supuestos y limitaciones. En adición se asume en estos cálculos tradicional que las probabilidad de fecundidad tienen una distribución normal y el tamaño de muestra es suficiente grande. Si las probabilidades de fecundidades son raras y los parámetros son cerca de cero vea el capítulo de métodos Bayesianos para calcular la fecundidad. En adición si la distribución de fecundidad no cumple con una distribución normal vea el capítulo de métodos Bayesianos para calcular la fecundidad. Es posible que una distribución gamma sea una mejor acercamiento a la distribución de fecundidad de una especie.

5.  **Relación entre las matriz de transiciones, fecundidad y clonaje**:

Este capítulo se enfoca en como relacionar las diferentes matrices de transiciones, fecundidad y clonaje. La suma de los tres tipo de matriz refleje el ciclo de vida de la especie estudiado. Separar las matriz en una de transición, fecundidad y clonaje ayuda a aclarar los procesos y patrones de la dinámica poblacional en adición que ciertos índices depende que la matriz sea separada. Por ejemplo para calcular el largo de vida de una especies (lifespan) se usa solamente la matriz de transición y o clonaje [@orive1993effective].

6.  **Métodos Bayesiano de calcular las transiciones y fecundidad**:

Este nuevo procedimiento incluido en un paquete de R, llamado **raretrans** tiene como objetivo resolver múltiples asuntos en la estimación de los parámetros de transición y fecundidad. Específicamente en la falta de datos de las transiciones raras y datos con parámetros sin sentido biológicos (ejemplo: supervivencia perfecta, ninguna mortandad). Aunque este paquete es nuevo y no ha sido implementado en múltiples estudios todavía, se espera que las funciones en este paquete sean herramientas útiles para los investigadores que trabajan con datos de dinámica poblacional especialmente cuando se trata de especies raras donde la recolección de datos es limitada a tamaño de muestras pequeñas [@tremblay2021population; @ospina2023effect].

7.  **Crecimiento poblacional**:

El crecimiento poblacional se refiere a si la población es estable, creciendo o reduciendo. Se presentará los métodos de calcular de forma simple y se discute algunos los supuestos y limitaciones. Se discute los diferentes tipos de índices de crecimiento poblacional y como se puede interpreta. En adición se presenta varias alternativas como calcular el crecimiento incluyendo métodos estocásticos y métodos de calcular los intervalos de credibilidad de $\lambda$.

8.  **Análisis de sensibilidad y elast##icidad**:

Los análisis de sensibilidad y elasticidad son herramientas para evaluar la importancia relativa de los cambios en los parámetros de la matriz de transición sobre el crecimiento poblacional. En este capítulo se presentará los métodos de calcular de forma simple y se discute algunos los supuestos y limitaciones. Se discute cual es la diferencias entre matriz de sensibilidad y elasticidad y como se puede interpretar los resultados como herramienta para el manejo de las especies para su conservación. Un ejemplo de la importancia de estos análisis se encuentra en los trabajos sobre la tortuga boba, *Caretta caretta* [@crouse1987stage; @crowder1994predicting] donde se ha encontrado que la supervivencia de las hembras adultas es el parámetro más importante para el crecimiento poblacional de la especie, mucho más que la supervivencia de los huevos (eso no quiere decir que no deberían protergerse los huevos). Lo que identifica es que para cada adulto que se protege tiene un potencial de cambio poblacional muchos más grande que salvar un huevo.

9.  **Indices de história de vida**:

Este capitulo recoge una diversidad de indices sobre la matriz y sus parámetros que se pueden calcular para evaluar la historia de vida de una especie. Estos índices son herramientas para evaluar el estado de la matriz para determinar si las condiciones de la matriz es adecuada para los analisis de dinámica poblacional. Indices de la dimensión de la matriz, egócidad, si la matriz tiene valores negativos, irredicubilidad, primitividad, y una serie de indices poblacional tal como estrura estable, valor reproductivo, analisis de convergencia y amortiguamiento.

10. **Dinámica de transiciones**:

La dinámica de las transiciones evalúa los cambios en parámetros como por ejemplo: tamaño poblacional, supervivencia, fecundidad y el efecto que pudiese tener sobre el crecimiento y las etapas de vida. Ejemplos, incluye como la distribución de las etapas al comienzo del estudio impacta en el crecimiento poblacional, o cómo la supervivencia de una etapa impacta en el crecimiento poblacional. En este capítulo se presenta los métodos para calcular de forma simple y se discute algunos de los supuestos y limitaciones. Gran parte de estos acercamiento fueron desarrollado por Stott y colegas [@stott2010boom; @mcdonald2016transients] y otros [@heggerud2023transient]. Estas acercamiento han sido usado en múltiples estudios de dinámica poblacional evaluando cómo los cambios de transiciones son dinámicos. La ventaja de esta acercamiento es que se puede evaluar los cambios en los parámetros de la matriz de transición y como impacta el crecimiento poblacional y no asume que los cambios necesariamente que lleguen a una población estable.

11. **Funciones de transferencias**:

Los métodos de funciones de transferencias son una herramienta para evaluar el impacto de los cambios en los parámetros de la matriz de transición sobre el crecimiento poblacional. Es un herramienta moderna de análisis de elasticidad. La desventaja de análisis de elasticidad es que asume que los cambios en los parámetros de la matriz de transición son pequeños y que el crecimiento poblacional es estable. En este capítulo se presenta los métodos para calcular de forma simple y se discute algunos de los supuestos y limitaciones y sus ventajas.

12. **Experimento de Respuesta de Tabla de Vida**:

Experimento de Respuesta de Tabla de Vida es un experimento diseñado para evaluar la respuesta de una especie a cambios en los parámetros de la matriz de transición tomando en cuenta múltiples matrices. Este experimento es una herramienta para evaluar como los cambios en los parámetros de la matriz de transición impacta el crecimiento poblacional. En este capítulo se presenta los métodos para calcular de forma simple y se discute algunos de los supuestos y limitaciones. Básicamente se calcula un promedio de de los parámetros de la matriz de transición y se evalúa como el crecimiento poblacional cambia con los cambios en los parámetros de la matriz de transición. Este experimento esta bien presentado en por Caswell [@caswell2001matrix] y ha sido usado en múltiples estudios de dinámica poblacional evaluando cómo los cambios de transiciones son dinámicos.

13. **Variación Espacial y Temporal: simulaciones**:

En este capítulo se presenta como hacer simulaciones de la dinámica poblacional para evaluar el efecto sobre el crecimiento poblacional debido a la variación espacial y/o temporal. Se presentan ejemplos de como hacer simulaciones de la dinámica poblacional usando el paquete de R **popbio** y **popdemo**. Este es un acercamiento parcialmente similar a los experimentos de respuesta de tabla de vida, pero en este caso se evalúa como la variación espacial y temporal impacta el crecimiento poblacional seleccionando al azar las matriz. Este es un acercamiento parcialmente similar a los experimentos de respuesta de tabla de vida, pero en este caso se evalúa como la variación espacial y temporal impacta el crecimiento poblacional seleccionando al azar las matriz y no basado en calcular un promedio de los parámetros de la matriz de transición y evaluando las diferencias.

14. **Impacto de datos sin sentidos**:

Este capítulo es *PRIMORDIAL* para los investigadores que trabajan con datos de dinámica poblacional y debería ser el capítulo donde se regrese continuamente para evaluar sus análisis e interpretaciones. Hay un dicho en inglés que dice, *Garbage in Garbage out*. **En otra palabras si los datos no tiene sentido biológico y matemático los resultados no sirven**. Múltiples ejemplos de datos sin sentido y como estos datos pueden impactar en los resultados y interpretación de los análisis de forma negativa. Algunos componentes incluidos en esta capitulo es el efecto de ciclos de vida incompleto y el efecto de calcular intervalos de confianza usando distribuciones normales cuando los parámetros no cumplen con una distribución normal. En adición se presenta el efecto de usar datos sin sentido biológico como por ejemplo supervivencia perfecta, fecundidad cero, etc.

15. **Un protocolo para informar sobre modelos discreto de estructura de población**:

En este capítulo se presenta un protocolo para informar sobre modelos discreto de estructura de población. Este protocolo es una guía para los investigadores para asegurar que toda la información necesaria es presente para evaluar críticamente sus manuscritos. Este capítulo es una traducción de **A standard protocol to report discrete stage-structured demographic information** [@gascoigne2023standard]. *Antes de publicar un estudio usando matrices de proyección se debería asegurar que cumple con la mayoría de las recomendaciones presentadas en este protocolo.*

16. **Estudios evolutivos de la dinámica poblacional: ejemplos con Orquídeas**:

17. **COMPADRE: Una base de datos de matrices de vida de plantas**:

Todos las publicaciones (revisado por pares, tesis, informes técnicos) que tienen matrices de vida de plantas están incluido en COMPADRE (por lo menos eso es el objetivo). En este capítulo se presenta la base de datos con un sub-grupo de especies (las orquídeas) y se evalúa como utilizar la base datos. La funciones (scripts) para extraer las matrices y analizar los datos está disponible en el paquete de R **RCompadre**. Se evalúa múltiples hipótesis sobre la dinámica poblacional de las orquídeas y se determina si hay patrones generales en la dinámica poblacional de las orquídeas entre grupos (por ejemplo terrestres vs. epífitas, distribución mundial, tiempo de estudios, etc). Este un capítulo para dar ideas a los investigadores que trabajan con datos de dinámica poblacional y como se puede hacer análisis de datos a gran escala.

19. **Conclusiones**:

En este capítulo se presenta las conclusiones generales del libro y se presenta las recomendaciones para futuras investigaciones en la dinámica poblacional. AL mismo tiempo se hace referencia a nuevos métodos y conceptos que no se han presentado en el libro.

## Sección de História

1.  **Historia breve de los PPM en orquídeas**:

Todo trabajo científico que hagamos hoy depende de los trabajos de los científicos que vinieron antes de nosotros. Conocer que se ha hecho antes nos ayuda a entender la hipótesis, métodos y lo que se conoce hasta el momento. En este capítulo se presenta una breve historia de la dinámica poblacional en orquídeas usando PPM. Se presenta un resumen de los primeros estudios y como estos estudios han impactado el desarrollo de la dinámica poblacional en orquídeas. En adición se presentan ciertos de los retos que todavía existen en el estudio de la dinámica poblacional en orquídeas y como estos retos pueden ser superados.

2.  **Carl Olaf Tamm el padre de la dinamica poblacional en orquídea**:

Carl Olaf Tamm fue el pionero en estudiar la dinámica poblacional de las orquídeas, específicamente *Dactylorhiza incarnata*, *Dactylorhiza sambucina*, *Orchis mascula* y *Listera ovata* [@tamm1948observations; @tamm1956further; @tamm1972survival]. Se presenta algunos de sus observaciones y interpretaciones. En adición se aprovecha para re-analizar algunos de los datos de Tamm usando los métodos modernos de dinámica poblacional.

Apéndice 1: **Lista de especies de Orquídeas estudiadas usando PPM**:

Lista de las especies de orquídeas que se han estudiado en la dinámica poblacional y la referencia de los estudios. EL tema principal de cada manuscrito/estudio esta presentado en una tabla para que el lector pueda buscar los estudios que le interesa.

Apéndice 2: **Hoja de datos de campo**:

Para facilitar el comienza de trabajos para nuevos investigadores en la dinámica poblacional de las orquídeas, se presenta como se prepará las hojas de datos de campo que puede ser usada para recolectar los datos. Esta hoja de datos es un ejemplo de como se puede recoger los datos de forma estandarizada y como se puede usar para hacer análisis de dinámica poblacional.

Apéndide 3: **Datos para análisis**:

En este apéndice se pone en acceso los datos para algunos de los análisis en los diferentes capítulos en adición de añadir los trabajos de Tamm ya que estos son difícil de acceso.

------------------------------------------------------------------------

## Paquetes de R principales usado en el libro

Los paquetes principales para el análisis de dinámica poblacional son los siguientes, aunque muchos otros fueron utilizados transformar datos, producir gráficos y para construir el libro.

-   *popbio*: un paquete para analizar datos de dinámica poblacional basado en funciones que se encuentran en el libro de Caswell [@caswell2001matrix] y en el libro de Morris y Doak [@morris2002quantitative] por edades o etapas [@popbio2007].

-   *popdemo*: un paquete que incluye Herramientas para modelar poblaciones y demografía utilizando modelos de proyección matricial, con implementaciones de modelos deterministas y estocásticos. Incluye proyección de población, índices de tamaño y crecimiento de la población a corto y largo plazo, análisis de perturbaciones, convergencia hacia la estabilidad o estacionaria [@popdemo2021].

-   *raretrans*: Funciones para crear modelos matriciales de población a partir de una combinación de datos sobre transiciones de etapa/edad con información previa bayesiana. Esto compensa los problemas estructurales causados por la falta de observaciones de transiciones raras y datos sin sentido biológicos [@raretrans2024] vea capítulo de métodos Bayesiano.

-   *Rage*: Funciones para calcular métricas de historia de vida utilizando modelos matriciales de población ("MPM"). Descrito en Jones [@Rage2022].

-   *RCompadre*: Un paquete para analizar datos recopilado en la base de datos de COM(P)ADRE: ese es un base de datos de matrices de vida de plantas y animales usando matrices [@jones2022rcompadre].

Otros paquetes que se usan para analizar datos, mayormente para manipular datos, hacer modelos estadísticos y visualización incluye:

-   *ggplot2*: \# para hacer gráficos
-   *dplyr*: \# para manipular datos
-   *tidyr* \# para manipular datos
-   *lubridate* \# para trabajar con fechas

## Libro digital y archivos de datos

El libro digital se encuentra en el siguiente enlace, donde el acceso a todas las funciones y datos están disponibles para reproducir los ejemplos utilizado en el libro.

https://raymondltremblay.github.io/Diagnostico_Poblacional/

## Lista de paquetes usados en el libro

```{r}
#install.packages("grateful", dependencies = TRUE)
library(grateful)
scan_packages()
```

Revisión:

RLT Sept 14, 2024

Elaine González Feb 12, 2025

RLT Feb 16, 2025
