{
  "hash": "944353ce266c14840ea0b449381e2eb8",
  "result": {
    "engine": "knitr",
    "markdown": "# Propiedades de las matrices y estimación de parámetros\n\nPor: Mariana Hernández-Apolinar y Paola Portillo Tzompa\n\nLas propiedades de una matriz de proyección poblacional determinan cómo se comporta una población a largo plazo bajo condiciones constantes. Este capítulo introduce las principales propiedades matemáticas y biológicas de las matrices poblacionales y explica por qué son centrales para interpretar la dinámica poblacional más allá del valor de λ.\n\n## Propiedades fundamentales de las matrices de proyección poblacional\n\nLas matrices de proyección poblacional poseen un conjunto de propiedades matemáticas que gobiernan la dinámica demográfica de las poblaciones a largo plazo. Entre estas propiedades se encuentran la estructura estable por estadios, el valor propio dominante (λ), el vector reproductivo y la convergencia asintótica de la población hacia un patrón dinámico estable.\n\nEn este capítulo se examinan estas propiedades desde una perspectiva biológica, mostrando cómo emergen de la estructura del ciclo de vida y de las tasas vitales que describen supervivencia, crecimiento y fecundidad. Se explica cómo la estructura estable de la población representa la distribución proporcional de individuos entre estadios cuando la población ha alcanzado su dinámica asintótica, y por qué esta estructura es clave para interpretar proyecciones poblacionales y comparaciones entre escenarios.\n\nAdemás, se introduce el concepto de valor reproductivo como una medida de la contribución relativa de cada estadio al crecimiento futuro de la población. Este capítulo se diferencia de los anteriores porque no se centra en el cálculo de λ ni en su sensibilidad a cambios paramétricos, sino en la comprensión de las propiedades estructurales que explican **por qué** las poblaciones exhiben determinados patrones de crecimiento, estabilidad o declive. Estas propiedades constituyen la base conceptual para análisis posteriores de elasticidad, LTRE y simulaciones poblacionales.\n\n## Propiedades matemáticas y cálculo computacional\n\nA continuación se ilustran las propiedades matemáticas de las matrices de proyección poblacional y su cálculo mediante herramientas computacionales.\n\n#### Librerías de R requeridas para el siguiente módulo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(popdemo)\nlibrary(popbio)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(scales)\nlibrary(Rage)\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n## Propiedades, supuestos e índices matriciales\n\nEn este capítulo aprenderemos sobre algunos índices que se usan con frecuencia en el análisis matricial. Estos índices nos ayudan a saber si una matriz es “buena” para trabajar y si los resultados que obtenemos son confiables.\n\nEl capítulo está dividido en dos partes:\n\n1.  **Índices sobre el estado de la matriz**\n\nAquí veremos características básicas que debe cumplir una matriz para que el análisis sea válido:\n\n-   **Dimensión cuadrada**: la matriz debe tener el mismo número de filas y columnas.\n-   **Ergocidad**: asegura que, con el tiempo, todas las partes del sistema se conecten.\n-   **No negatividad**: los valores de la matriz no pueden ser negativos.\n-   **Irreducibilidad**: indica que no se puede dividir la matriz en bloques independientes.\n-   **Primitividad**: garantiza que, después de varias iteraciones, la matriz se estabiliza.\n\n2.  **Índices sobre el comportamiento a largo plazo**\n\nEstos se basan en modelos de proyección poblacional (MPP) y nos permiten entender cómo cambia la población antes y después de un disturbio:\n\n-   **Análisis de convergencia**: mide si la población tiende a una estructura estable.\n-   **Análisis de amortiguamiento**: indica qué tan rápido se alcanza esa estabilidad.\n-   **Valor reproductivo**: muestra la importancia de cada clase en la reproducción futura.\n-   **Estructura estable**: describe la distribución de la población cuando todo se estabiliza.\n\nSi quieres profundizar en estos índices, te recomiendo consultar [@caswell2001matrix] y [@stott2011framework].\n\n## Construcción de una matriz poblacional\n\nEl primer paso en el análisis matricial es construir una matriz de transición poblacional, la cual resume en una tabla la supervivencia,la reproducción y transiciones de los individuos en diferentes etapas o categorías de edad. Cada fila y columna de la matriz representa un estadio del ciclo de vida de la especie, y cada elemento dentro de la matriz describe la transición de un estadio a otro en un intervalo de tiempo determinado (por ejemplo, de un año a otro).\n\n## Matriz de proyección poblacional (MPP)\n\nUna matriz de proyección poblacional (MPP) es una matriz cuadrada que permite describir y predecir la dinámica de una población a través del tiempo. En esta se organizan las probabilidades de transición entre categorías de tamaño o estado (plántulas, juveniles, adultos, etc.) junto con la fecundidad o reproducción de los individuos.\n\nLa MPP se utiliza para proyectar la estructura de una población en el futuro, a partir de su composición actual. Así, constituye la base para calcular tasas de crecimiento poblacional, estructuras estables, valores reproductivos y otros índices demográficos fundamentales.\n\nA continuación se construye la matriz poblacional de *Lepanthes rubripetala*. Esta matriz se compone de cuatro estados: plántulas (PL), juveniles (J), adultos no reproductivos (NR) y adultos reproductivos (AR).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Capturar los datos de la matriz para L. rubripetala (Tremblay et al. 2015)\nLr1 <- matrix(c(0.4324, 0,      0,     0.15,\n                0.3784, 0.8459, 0,     0,\n                0,      0.0034, 0.7954,0.2300,\n                0,      0.0890, 0.1841,0.7510), byrow=TRUE,ncol=4)\n\n# Capturar las categorias de estado\nestadios <- c(\"PL\", \"J\", \"NR\", \"AR\")\ncolnames(Lr1) <- rownames(Lr1) <- estadios\n\n# Obtener la matriz L. rubripetala\nLr1 <- matrix(Lr1[1:4, ], nrow = 4, dimnames = list(estadios, estadios))\nLr1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       PL      J     NR    AR\nPL 0.4324 0.0000 0.0000 0.150\nJ  0.3784 0.8459 0.0000 0.000\nNR 0.0000 0.0034 0.7954 0.230\nAR 0.0000 0.0890 0.1841 0.751\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Supuestos de la matriz poblacional\n\n### Dimensión cuadrada\n\nLas matrices poblacionales deben tener dimensiones cuadradas, es decir, deben tener el mismo número de renglones que de columnas. Esta característica es importante porque cada columna y renglón representa una categoría de edad o un estado del ciclo de vida de la especie. Las columnas representa categoría de los individuos al inicio del estudio, mientras que los renglones su tránsito a otra después de un periodo de tiempo. Si la matriz no es cuadrada, no hay correspondencia que permita comparar el número de individuos por categoría al inicio y final de un periodo de estudio, por lo que será imposible estimar la tasa de crecimiento poblacional. En el caso de *L. rubripetala*, la matriz poblacional tiene 4 renglones y 4 columnas, por lo que cumple con la propiedad de dimensión cuadrada. Esto puede verificarse fácilmente en *R* usando la función *dim*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(Lr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4 4\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Ergócidad\n\nDecimos que la propiedad de ergodicidad se cumple cuando el crecimiento asintótico predicho por matriz es independiente de la estructura poblacional inicial considerada en el estudio. En otras palabras, sin importar el estado inicial de la población, su comportamiento converge a una estructura estable y a una tasa de crecimiento constante a largo plazo. Si una matriz poblacional no es ergódica, el crecimiento poblacional depende de la estructura poblacional inicial, lo que implica que el promedio o la tasa de crecimiento poblacional no son buenos predictores del comportamiento poblacional a largo plazo [@mangalam2022ergodic]. Para comprobar si la matriz es ergódica puede emplearse la función *isErgodic* del paquete **popbio** en **R**. Esta función da como resultado el valor lógico \"TRUE\" si la matriz es ergódica y \"FALSE\" en el caso contrario. En *L. rubripetala* se espera que la matriz sea ergódica, ya que los autores reportaron que la población alcanza tanto una estructura estable como una tasa de crecimiento constante en el tiempo [@tremblay2015stable].\n\n\n::: {.cell}\n\n```{.r .cell-code}\nisErgodic(Lr1, digits=5, return.eigvec=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nUna matriz no cumple la condición de ergodicidad cuando, por ejemplo, ningún individuo logra pasar del estado de plántula al juvenil ni al adulto. En este caso, la población queda “atascada” en las primeras etapas y no puede alcanzar una estructura estable. Si evaluamos esta matriz con la función `isErgodic` del paquete popbio en R, el resultado será FALSE. Esto indica que:\n\n-   El crecimiento poblacional depende de la estructura inicial, y\n-   No se puede esperar que la población alcance una estructura estable ni una tasa de crecimiento constante a largo plazo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Capturar los datos de la matriz para L. rubripetala (Tremblay et al. 2015)\nLr1_No_erg <- matrix(c(0.4324, 0.,      0.,     0.150,\n               0., 0.8459, 0.,     0.,\n               0.,      0.0034, 0.7954,0.2300,\n               0.,      0.0890, 0.1841,0.7510), byrow=TRUE,ncol=4)\n\nplot_life_cycle(Lr1_No_erg, stages = estadios, fontsize = 8)\n```\n\n::: {.cell-output-display}\n![](110-Propriedades_files/figure-pdf/Indice5-1.png){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nisErgodic(Lr1_No_erg, digits = 4, return.eigvec = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Elementos no negativa\n\nUna matriz poblacional debe ser no negativa, lo que significa que todas sus entradas son mayores o iguales a cero. ¿Por qué? Porque cada valor representa el número o la proporción de individuos que pasan de una etapa a otra. Tener valores negativos no tendría sentido biológico: no puede haber “menos” individuos que los existentes.\n\nAdemás, si la matriz tuviera elementos negativos:\n\n-   No podríamos comparar correctamente las categorías de edad o estado.\n-   Sería imposible calcular la tasa de crecimiento poblacional.\n\nEn el caso de *L. rubripetala*, la matriz cumple esta condición, ya que todos sus valores son mayores o iguales a cero. En R, esto se puede verificar con la función `isPositive`, que devuelve:\n\n-   TRUE si la matriz es no negativa,\n-   FALSE si contiene algún valor negativo\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# No negativa \n\nIsPositive <- function(mat) {\n  if (all(mat >= 0)) {\n    return(TRUE)\n  } else {\n    return(FALSE)\n  }\n}\n\nIsPositive(Lr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nA continuación se muestra un ejemplo de una matriz que no cumple la propiedad de no negatividad. En este caso, el elemento ubicado en la posición (4, 3) es negativo, lo que indica que la transición desde la categoría adulto reproductivo hacia adulto no reproductivo tiene un valor inválido.\n\nAl evaluar esta matriz con la función `isPositive` en R, el resultado es FALSE. Esto significa que:\n\n-   La matriz no es válida para el análisis de dinámica poblacional.\n-   No se puede esperar que la población alcance una estructura estable ni una tasa de crecimiento constante a largo plazo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Capturar los datos de la matriz para L. rubripetala (Tremblay et al. 2015)\nLr1_No_pos<- matrix(c(0.4324, 0,      0,     0.15,\n               0.3784, 0.8459, 0,     0,\n               0,      0.0034, 0.7954,-0.2300,\n               0,      0.0890, 0.1841,0.7510), byrow=TRUE,ncol=4)\n\nIsPositive(Lr1_No_pos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Irreducibilidad\n\nUna matriz de transición poblacional debe ser irreducible, lo que significa que todas sus categorías están conectadas y existe al menos una ruta que permite llegar desde cualquier estado a los demás. Esta propiedad es esencial porque, si la matriz no es irreducible, la población no podrá alcanzar una estructura estable ni una tasa de crecimiento constante a largo plazo.\n\nEn el caso de *L. rubripetala*, la matriz es irreducible: todas las etapas del ciclo de vida están conectadas y existe una ruta entre ellas. Para comprobar esta propiedad en R, se utiliza la función `isIrreducible` del paquete popdemo, que devuelve:\n\n-   TRUE si la matriz es irreducible,\n-   FALSE si no lo es.\n\nEs importante destacar que no todas las matrices reducibles son inválidas. En algunos casos, pueden aceptarse, por ejemplo, en especies con etapas que no influyen en el crecimiento poblacional, como las fases postreproductivas en mamíferos (humanos, ballenas, etc.).\n\nEn resumen, para *L. rubripetala*, la función `isIrreducible` devuelve TRUE, lo que confirma que todas las categorías están conectadas y que la población puede alcanzar una estructura estable y una tasa de crecimiento constante a largo plazo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nisIrreducible(Lr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nA continuación se muestra un ejemplo de matriz en la que el cuarto estadio no presenta valores de reproducción. Al evaluar esta matriz con la función `isIrreducible` en R, el resultado es FALSE.\n\n¿Por qué ocurre esto? Porque no existe un vínculo entre la categoría plántula y la categoría adulto reproductivo, lo que significa que la presencia de plántulas en la población no contribuye a la reproducción.\n\nEsta ausencia de conexión provoca dos problemas:\n\n-   Un ciclo de vida incompleto, como se observa en la imagen.\n-   Una población que no podrá alcanzar una estructura estable ni una tasa de crecimiento constante a largo plazo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLr1_Irr <- matrix(c(0.4324,  0.,       0.0,     0,\n                    0.3784,  0.8459,   0,       0,\n                    0.,      0.0034,   0.7954,  0.2300,\n                    0,       0.0890,   0.1841,  0.7510), byrow=TRUE,ncol=4)\n\nplot_life_cycle(Lr1_Irr, stages = estadios, fontsize = 8)\n```\n\n::: {.cell-output-display}\n![](110-Propriedades_files/figure-pdf/unnamed-chunk-3-1.png){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nisIrreducible(Lr1_Irr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Primitividad\n\nUna matriz de transición poblacional debe ser primitiva, lo que significa que, al elevarla a potencias altas, se obtiene un único valor positivo dominante (la tasa de crecimiento poblacional). Esta propiedad es clave porque asegura que la población alcanzará una estructura estable y una tasa de crecimiento constante a largo plazo.\n\nEn el caso de *L. rubripetala*, la matriz es primitiva: al elevarla a potencias altas, aparece un único valor positivo. En R, esto se puede comprobar con la función `isPrimitive` del paquete popdemo, que devuelve:\n\n-   TRUE si la matriz es primitiva,\n-   FALSE si no lo es.\n\nUna matriz no primitiva tendría una dinámica inestable a largo plazo, como ocurre en poblaciones con comportamiento cíclico, donde las proporciones entre categorías oscilan sin llegar a estabilizarse.\n\nEs importante señalar que:\n\n-   Toda matriz irreducible es primitiva,\n-   Pero no toda matriz primitiva es irreducible. Por ejemplo, una matriz puede ser primitiva sin ser irreducible si incluye un ciclo de vida completo, pero alguna etapa no influye en el crecimiento poblacional (como fases postreproductivas).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nisPrimitive(Lr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Índices de descripción de la matriz poblacional\n\nEn esta sección se revisan los índices poblacionales obtenidos a partir del análisis de matricial, los cuales se estiman una vez que ha verificado que cumplen con los supuestos. Estos índices permiten comprender el comportamiento de la población a largo plazo y anticipar cómo se espera que se comporte en el tiempo. Los índices que se abordan a continuación son: **estructura estable**, **valor reproductivo**, **análisis de convergencia** y **análisis de amortiguamiento**. Todos estos se calculan a partir de la matriz de transición poblacional y del vector de la estructura poblacional observada al inicio del estudio.\n\n------------------------------------------------------------------------\n\n### Estructura estable\n\nLa estructura poblacional estable (W, también conocida como eigenvector derecho) indica la proporción esperada de individuos en cada categoría de edad o estado cuando la población ha alcanzado el equilibrio a largo plazo. Por ejemplo, en L. rubripetala se espera que la estructura estable sea:\n\n-   Plántulas: 0.088\n-   Juveniles: 0.206\n-   Adultos no reproductivos: 0.369\n-   Adultos reproductivos: 0.337\n\nEste índice supone que la tasa de crecimiento poblacional ($\\lambda$) se mantiene constante en el tiempo, lo cual solo ocurre bajo condiciones ambientales estables. Sin embargo, en la naturaleza esto es poco común. Además, la estructura estable asume que el periodo de muestreo y las condiciones abióticas y bióticas son típicas y no cambian.\n\nEn la revisión de Williams y colaboradores [@williams2011distance], se reportó que más del 80% de las poblaciones analizadas no cumplían con la condición de estructura estable, especialmente en especies con matrices grandes (n × n) y tiempos generacionales prolongados. De manera similar, Tremblay (com. pers.) observó que la mayoría de las orquídeas estudiadas no estaban en estructura estable al inicio del muestreo poblacional.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Estructura estable de estados\n\nstable.stage(Lr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        PL          J         NR         AR \n0.08789851 0.20619682 0.36907404 0.33683063 \n```\n\n\n:::\n:::\n\n\nUno puede visualizar la estructura poblacional usando el código siguiente.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWmax <- stable.stage(Lr1)\nWdf = data.frame(Wmax)\nWdf$Categorias = c(\n  \"Plántulas\",\n  \"Juveniles\",\n  \"Adultos no reproductivos\",\n  \"Adultos reproductivos\"\n)\nWdf$Categorias = factor(\n  Wdf$Categorias,\n  levels = c(\n    \"Plántulas\",\n    \"Juveniles\",\n    \"Adultos no reproductivos\",\n    \"Adultos reproductivos\"\n  )\n)\nlibrary(ggplot2)\n\nggplot(Wdf, aes(y = Wmax, x = Categorias)) +\n  geom_bar(stat = \"identity\", aes(fill = \"blue\")) +\n  labs(\n    title = \"Estructura estable de estados esperada\",\n    x = \"Etapas\",\n    y = \"Proporción\"\n  ) +\n  rlt_style_fill()+\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))+\n  theme(legend.position=\"null\")\n```\n\n::: {.cell-output-display}\n![](110-Propriedades_files/figure-pdf/Indice10-1.png){fig-pos='H'}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Valor reproductivo\n\n::: img-float\n![*Spathoglottis plicata*. Foto: Tremblay](images/Spathoglottis_plicata_Tremblay.jpeg){style=\"float: left; margin: 10px;width: 40% ; \"}\n:::\n\nEl valor reproductivo (v, también llamado eigenvector izquierdo) indica la contribución esperada de cada categoría de edad o estado a la reproducción de la población.\n\nEn el caso de L. rubripetala, los valores reproductivos esperados son:\n\n-   Plántulas: 1.00\n-   Juveniles: 1.52\n-   Adultos no reproductivos: 2.32\n-   Adultos reproductivos: 2.66\n\nEste índice es muy útil porque muestra qué etapas son más importantes para el crecimiento poblacional a largo plazo. La primera categoría siempre tiene un valor de 1.00, ya que representa el inicio del ciclo de vida y sirve como referencia para calcular los demás valores.\n\nAdemás, el valor reproductivo ayuda a definir estrategias de manejo. Por ejemplo:\n\n-   En *Spathoglottis plicata*, una orquídea terrestre invasora, las acciones de control deberían enfocarse en las categorías con mayor valor reproductivo, porque son las que más contribuyen al crecimiento poblacional.\n\n-   Por el contrario, si se busca remover individuos con el menor impacto posible, conviene actuar sobre las etapas con valores reproductivos bajos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Valor reproductivo\n\nreproductive.value(Lr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      PL        J       NR       AR \n1.000000 1.519043 2.316113 2.664676 \n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Análisis de convergencia y amortigamiento (\"Damping ratio\")\n\nEl análisis de convergencia mide el tiempo esperado para que una población alcance su estructura estable y un crecimiento asintótico después de un disturbio. Es decir, indica qué tan rápido la población regresa a su estructura estable tras una perturbación [@stott2011framework]. Este comportamiento se cuantifica mediante el índice de amortiguamiento (damping ratio), que evalúa la influencia del valor propio subdominante, $\\lambda_2$, durante el periodo de convergencia.\n\nEl índice se expresa a través del cociente entre el valor propio dominante, $\\lambda_1$, y el valor absoluto del subdominante $$\\mathbf{\\rho=\\frac{\\lambda_1}{\\left|\\lambda_2\\right|}}$$; dónde $\\rho$ representa el índice de amortiguamiento, $\\lambda_1$ corresponde al valor propio dominante de la matriz de transición poblacional y $\\lambda_2$ al módulo del segundo valor propio más grande. Este índice no tiene unidades y es independiente de la estructura inicial de la población.\n\nEn el caso de *L. rubripetala*, al calcular los valores propios de la matriz con la función **eigen**, se obtiene un valor dominante de $\\lambda_1= 1.00721$ y un valor subdominante de $\\lambda_2= 0.8319$. De esta manera el índice de amortiguamiento es:\n\n$$\n\\rho = \\frac{\\lambda_1}{|\\lambda_2|} = \\frac{1.00721}{|0.83192|} \\approx 1.21\n$$\n\nEl valor obtenido indica que la población converge hacia su estructura estable tras un disturbio; aunque, lentamente.\n\nEs importante señalar que la interpretación de este índice depende de la escala temporal con que se construyó la matriz. Si bien la mayoría de los estudios poblacionales utilizan datos anuales [@crone2011plant], también existen estudios con periodos de muestreo mensuales, bimensuales, estacionales o bianuales, los cuales se establecen de acuerdo con el ciclo de vida de la especie estudiada.\n\n\n::: {.cell}\n\n```{.r .cell-code}\neigen(Lr1)$values # la lista de valores propios de la matriz Lr1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.0072061+0.00000000i 0.8319189+0.00000000i 0.4927875+0.06468183i\n[4] 0.4927875-0.06468183i\n```\n\n\n:::\n\n```{.r .cell-code}\nDR = eigen(Lr1)$values[1] / abs(eigen(Lr1)$values[2])\n\nDR\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.210702+0i\n```\n\n\n:::\n\n```{.r .cell-code}\ndr(Lr1) # usando la función \"dr\" para \"damping ratio\" en el paquete \"popdemo\"\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.210702\n```\n\n\n:::\n:::\n\n\n### Graficación del índice de amortiguamiento\n\nEl comportamiento del índice de amortiguamiento se puede visualizar mediante una gráfica de líneas, que muestra cómo responde un sistema ante un cambio súbito (un “paso de entrada”) y cómo varía esa respuesta en el tiempo según diferentes niveles de amortiguamiento.\n\nPara facilitar la comprensión, en el siguiente bloque se incluye el código que genera una gráfica ilustrando el comportamiento de una población perturbada:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# --- Definir los parametros ---\n# Población inicial en el tiempo t=0. Ese el punto de equilibrio inicial.\npoblacion_inicial <- 1000\n\n# Factores de amortiguamiento para graficar.\n# 0,3 = Subamortiguado (oscila)\n# 1,0 = Críticamente amortiguado (retorno más rápido sin oscilación)\n# 2,0 = Sobreamortiguado (retorno lento sin oscilación)\namortigamento <- c(0.3, 1.0, 2.0, 3.0)\n\n# Frecuencia de la oscilación (omega_n).\nfrecuencia <- 0.5\n\n# Tiempo total para la simulación\ntiempo_total <- 50\n\n# Paso de tiempo para la simulación (más pequeño para una curva más suave)\netapa_tiempo <- 0.1\n\n# --- Generate the Damped Oscillation Data for Multiple Ratios ---\n# Create an empty data frame to store all the data\ntodo_data_df <- data.frame()\n\n# Recorra cada relación de amortiguamiento para generar los datos\nfor (zeta in amortigamento) {\n  # Create a sequence of time points\n  time_points <- seq(0, tiempo_total, by = etapa_tiempo)\n\n  # Calculate the population at each time point based on the damping ratio.\n  # The mathematical form of the step response changes depending on the damping ratio.\n\n  if (zeta < 1) {\n    # Underdamped case: damped sine wave\n    omega_d <- frecuencia * sqrt(1 - zeta^2)\n    population_data <- poblacion_inicial *\n      (1 -\n        exp(-zeta * frecuencia * time_points) *\n          (cos(omega_d * time_points) +\n            (zeta / sqrt(1 - zeta^2)) * sin(omega_d * time_points)))\n  } else if (zeta == 1) {\n    # Critically Damped case\n    population_data <- poblacion_inicial *\n      (1 - exp(-frecuencia * time_points) * (1 + frecuencia * time_points))\n  } else {\n    # Overdamped case\n    s1 <- -zeta * frecuencia + frecuencia * sqrt(zeta^2 - 1)\n    s2 <- -zeta * frecuencia - frecuencia * sqrt(zeta^2 - 1)\n    population_data <- poblacion_inicial *\n      (1 -\n        (s2 * exp(s1 * time_points) - s1 * exp(s2 * time_points)) / (s2 - s1))\n  }\n\n  # Add the data for the current damping ratio to a temporary data frame\n  temp_df <- data.frame(\n    Time = time_points,\n    Population = population_data,\n    DampingRatio = factor(zeta) # Store damping ratio as a factor for coloring\n  )\n\n  # Bind the temporary data frame to the main data frame\n  todo_data_df <- rbind(todo_data_df, temp_df)\n}\n\n# --- Create the Plot using ggplot2 ---\nggplot(todo_data_df, aes(x = Time, y = Population, color = DampingRatio)) +\n  # Add the lines for each damping ratio\n  geom_line(linewidth = 1.2) +\n  # Set the title and labels\nlabs(\n  title = \"El efecto de amortigamento \\n sobre el tamaño de población\",\n  subtitle = \"La población se estabiliza a un equilibrio de 1000\",\n  x = \"Tiempo\",\n  y = \"Tamaño poblacional\",\n  color = expression(\"Amortigamento (\" * zeta * \")\")\n) +\n  # Customize the plot theme for better aesthetics\n  rlt_style_colour() +\n  theme_minimal(base_size = 14) +\n  theme(\n    plot.title = element_text(hjust = 0.5, face = \"bold\"),\n    plot.subtitle = element_text(hjust = 0.5),\n    axis.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](110-Propriedades_files/figure-pdf/Indice13-1.png){fig-pos='H'}\n:::\n:::\n\n\n### Intepretación del gráfico de amortiguamiento\n\nLa figura resultante ilustra el efecto de diferentes coeficientes de amortiguamiento en la respuesta de una población a un cambio súbito. El gráfico muestra cuatro comportamientos distintos para la población perturbada y su retorno a un estado de equilibrio, correspondiente a un tamaño poblacional de 1000 individuos.\n\nLa respuesta de la población ante cuatro índices de amortiguamiento es la siguiente:\n\n• Subamortiguado (ζ=0.3): Esta es la respuesta oscilante. El sistema sobrepasa el punto de equilibrio y luego oscila, con el tiempo la amplitud de las oscilaciones disminuyen gradualmente hasta estabilizarse en el equilibrio.\n\n• Amortiguado críticamente (ζ=1.0): Esta es la respuesta más rápida, la cual alcanza el equilibrio sin oscilaciones ni sobreamortiguaciones. Se considera la respuesta ideal para sistemas que requieren un retorno rápido y estable al valor objetivo.\n\n• Sobreamortiguado (ζ=2.0): Esta respuesta es lenta y se aproxima al punto de equilibrio sin oscilaciones. En comparación con el caso críticamente amortiguado, tarda mucho más en estabilizarse, ya que la fuerza de amortiguamiento es muy grande.\n\n• Sobreamortiguado (ζ=3.0): Similar al caso anterior, pero con un amortiguamiento aún mayor. La respuesta es muy lenta y se acerca al equilibrio de manera gradual sin oscilaciones.\n\n#### Tiempo de Convergencia\n\nEl tiempo de convergencia es el periodo estimado que tarda la población en alcanzar su estructura estable. Este índice es relevante porque facilita entender el comportamiento poblacional a largo plazo. En **R** este cálculo puede realizarse con dos funciones del paquete **popdemo**: **dr** y **convt**. La función **dr** calcula el amortiguamiento y a partir de éste puede estimarse el tiempo de la convergencia de la siguiente manera:\n\n$$\nt = \\frac{\\log(dr)}{\\log(x)}\n$$\n\ndónde\n\n-   $dr$ es el índice de amortiguamiento (damping ratio)\n-   $x$ es un factor de comparación\n-   $t$ representa el tiempo en la misma unidad en que se construyó la matriz (días, meses, años, etc.).\n\nEl análisis de amortiguamiento estima la rapidez con la que una población converge a su estructura estable después de un disturbio [@jiang2020life]. El índice de amortiguamiento ($d > 0$) sugiere que mientras mayor sea su valor, más rápida será la convergencia. El tiempo de amortiguamiento se calcula como: $\\tau=1/d$, dónde $\\tau$ expresa la duración del proceso de convergencia en unidades de tiempo consistentes con la matriz poblacional. Cabe señalar que, se ha demostrado que existe una relación entre el índice de amortiguamiento y el tiempo generacional de una especie [@jiang2020life].\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndr(Lr1, return.time = TRUE, x = 10) # cuanto tiempo toma aumentar la población de veces \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$dr\n[1] 1.210702\n\n$t\n[1] 12.04278\n```\n\n\n:::\n:::\n\n\nA partir de la la función $contv$ del paquete **popdemo** se puede estimar el tiempo esperado en que una población alcanza su estructura estable, considerando la estructura poblacional observada al inicio del estudio. Esta función simula el modelo y determina manualmente cuándo la población converge, dado un nivel de exactitud especifico (*accuracy*). Entre más estricta sea la exactitud, mayor será el tiempo de convergencia. Para utilizar esta función es necesario indicar la estructura inicial, es decir, el número de individuos en cada estadio. En el caso de *L. rubripetala* se espera que el tiempo de convergencia sea de 18 ciclos (meses) para alcanzar su estructura estable.\n\nPor ejemplo, si se comienza con una población inicial de 8, 20, 27 y 34 individuos en las categorías de plántulas, juveniles, adultos no reproductivos y adultos reproductivos, respectivamente, la población alcanzaría en 6 meses, aproximadamente, la estructura estable. En contraste, si la población inicial estuviera sesgada (compuesta únicamente por plántulas, por ejemplo), el tiempo de convergencia sería mucho mayor. Este enfoque resulta muy útil al definir estrategias de conservación; por ejemplo, al establecer una nueva población con una distribución inicial determinada.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn0 <- c(8, 20, 27, 34) # la estructura de la población inicial\n\nconvt(Lr1, accuracy = 1e-4, vector = n0, iterations = 10000) # la estructura poblacional inicial\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18\n```\n\n\n:::\n:::\n\n\nDado que el tiempo de convergencia es un índice que representa el periodo esperado para que una población alcance su estructura estable, se puede calcular variando la cantidad de individuos en las diferentes edades o estados al llevar a cabo una simulación.\n\nPor ejemplo, se estima que *L. rubripetala* alcanzaría la estructura estable en 25 meses, si la población inicia con una población sesgada a plántulas (n = 1000) y, por lo tanto, sin la presencia de individuos de los estados posteriores.\n\n### Graficación del tiempo de convergencia al estado estable de cada etapa de vida\n\nLa población comienza en cada etapa con 100 individuos y se simula durante 22 pasos de tiempo. El gráfico resultante muestra cómo la población converge a su estructura estable a lo largo del tiempo, con cada etapa representada por una línea de color diferente. La línea horizontal indica el valor de la proporción de la etapa estable y la linea vertical representa a que tiempo se espera que la etapa llegua a su nivel de estructura estable.\n\nNota que si las condiciones se quedan igual en el tiempo se espera que la población converja a una estructura estable, es decir, que la proporción de individuos en cada etapa se mantenga constante a lo largo del tiempo. En este caso, la proporción de individuos en cada etapa converge a 0.088, 0.206, 0.369 y 0.337 para las categorías de plántulas, juveniles, adultos no reproductivos y adultos reproductivos, respectivamente 3, 17, 15 y 9 periodos (el tiempo de re-muestreo correspondiente a la construcción de la matrix).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Este script utiliza un enfoque de matriz para modelar las dinámicas de una\n# población de 4 etapas (por ejemplo, clases de edad o estadios de vida).\n# Demuestra cómo una distribución de población converge a un estado estable.\n\n# Instalar y cargar el paquete ggplot2 para el trazado\n# install.packages(\"ggplot2\")\nlibrary(ggplot2)\n\n# --- Definir Parámetros de Simulación ---\n# Población inicial en el tiempo t=0 para cada etapa.\n# Una distribución inicial uniforme es un buen punto de partida para observar la convergencia.\ninitial_population <- c(100, 100, 100, 100)\n\n# Número total de pasos de tiempo para la simulación\ntotal_time_steps <- 22\n\n# --- Definir la Matriz de Transición de la Población (Leslie Matrix) ---\n# Se utiliza la matriz proporcionada por el usuario.\ntransition_matrix <- matrix(c(0.4324, 0, 0, 0.15,\n                              0.3784, 0.8459, 0, 0,\n                              0, 0.0034, 0.7954, 0.2300,\n                              0, 0.0890, 0.1841, 0.7510),\n                    nrow = 4,\n                    byrow = TRUE\n)\n\n# --- Simular la Dinámica de la Población y Calcular Proporciones ---\n# Nombres de las etapas en el orden especificado\nstage_names <- c(\n  \"juvenil\",\n  \"plántula\",\n  \"adulto no reproductivo\",\n  \"adulto reproductivo\"\n)\n\n# Crear un data frame para almacenar los resultados de la simulación\nall_data_df <- data.frame(\n  Time = integer(),\n  Proportion = numeric(),\n  Stage = character()\n)\n\n# Vector de población actual (distribución inicial)\nn_current <- initial_population\n\n# Bucle para simular cada paso de tiempo\nfor (t in 0:total_time_steps) {\n  # Calcular la proporción de la población en cada etapa\n  current_proportions <- n_current / sum(n_current)\n\n  # Crear un data frame temporal para este paso de tiempo\n  temp_df <- data.frame(\n    Time = rep(t, 4),\n    Proportion = current_proportions,\n    Stage = factor(stage_names, levels = stage_names) # Se usa factor para ordenar las etapas\n  )\n\n  # Añadir los datos al data frame principal\n  all_data_df <- rbind(all_data_df, temp_df)\n\n  # Proyectar la población al siguiente paso de tiempo\n  # Multiplicación de la matriz de transición por el vector de población\n  n_next <- transition_matrix %*% n_current\n  n_current <- n_next\n}\n# --- Calcular la Distribución de Etapa Estable (SSD) ---\n# Se calcula el vector propio derecho (eigenvector) del valor propio dominante.\n# Este vector representa la proporción de individuos en cada etapa en el estado estable.\neigen_results <- eigen(transition_matrix)\n\n# Encontrar el valor propio dominante (más grande)\ndominant_eigenvalue <- max(Re(eigen_results$values))\n\n# Encontrar el vector propio derecho correspondiente (eigenvector)\nstable_stage_distribution_raw <- Re(eigen_results$vectors[, which.max(Re(\n  eigen_results$values\n))])\n\n# Normalizar el vector propio para que sume 1\nstable_stage_distribution <- stable_stage_distribution_raw /\n  sum(stable_stage_distribution_raw)\nstable_stage_distribution_df <- data.frame(\n  Stage = factor(stage_names, levels = stage_names),\n  Proportion = stable_stage_distribution\n)\n\n# --- Calcular el Tiempo de Convergencia para cada Etapa ---\n# Definir una tolerancia para la convergencia (por ejemplo, 1% de la proporción de SSD)\ntolerance <- 0.01\n\n# Crear un data frame para almacenar los tiempos de convergencia\nconvergence_times_df <- data.frame(\n  Stage = character(),\n  Time = numeric()\n)\n\n# Bucle a través de cada etapa para encontrar el primer paso de tiempo donde\n# la proporción está dentro de la tolerancia de la SSD\nfor (i in 1:length(stage_names)) {\n  stage_name <- stage_names[i]\n  ssd_proportion <- stable_stage_distribution_df[\n    stable_stage_distribution_df$Stage == stage_name,\n    \"Proportion\"\n  ]\n\n  # Filtrar los datos para la etapa actual\n  stage_data <- all_data_df[all_data_df$Stage == stage_name, ]\n\n  # Encontrar la primera fila donde la proporción está dentro de la banda de tolerancia\n  convergence_time <- stage_data$Time[which(\n    abs(stage_data$Proportion - ssd_proportion) <= tolerance\n  )[1]]\n\n  if (!is.na(convergence_time)) {\n    convergence_times_df <- rbind(\n      convergence_times_df,\n      data.frame(\n        Stage = stage_name,\n        Time = convergence_time\n      )\n    )\n  }\n}\n\n# La función `factor` es necesaria para garantizar que los nombres de las etapas\n# en `convergence_times_df` se muestren en el orden correcto.\nconvergence_times_df$Stage <- factor(convergence_times_df$Stage, levels = stage_names)\n\nsubexpr <- bquote(\"El crecimiento anual de la población es \" * lambda == .(round(dominant_eigenvalue, 4)))\n\n# --- Crear el Trazado Usando ggplot2 ---\npopulation_plot <- ggplot(\n  all_data_df,\n  aes(x = Time, y = Proportion, color = Stage)\n) +\n  geom_line(linewidth = 1.2) +\n  # Añadir líneas horizontales para la distribución de etapa estable\n  geom_hline(\n    data = stable_stage_distribution_df,\n    aes(yintercept = Proportion, color = Stage),\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  # Añadir líneas verticales para el tiempo de convergencia\n  geom_vline(\n    data = convergence_times_df,\n    aes(xintercept = Time, color = Stage),\n    linetype = \"dotted\",\n    linewidth = 1.0\n  ) +\nlabs(\n  title = \"Convergencia a la distribución estable \",\n  subtitle = subexpr,\n  x = \"Paso de Tiempo\",\n  y = \"Proporción de la Población\",\n  color = \"Etapa de Vida\"\n) +\n  rlt_style_colour() +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(hjust = 0.5, face = \"bold\"),\n    plot.subtitle = element_text(hjust = 0.5),\n    axis.title = element_text(face = \"bold\")\n  ) +\n  xlim(0, max(all_data_df$Time))\n\n# Imprimir el trazado final\nprint(population_plot)\n```\n\n::: {.cell-output-display}\n![](110-Propriedades_files/figure-pdf/indice16-1.png){fig-pos='H'}\n:::\n:::\n\n\nEstas propiedades estructurales permiten comprender el significado biológico de la tasa de crecimiento poblacional introducida en el capítulo sobre crecimiento poblacional.\n",
    "supporting": [
      "110-Propriedades_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}