{
  "hash": "0f28c7c57295321ba8e1c43d37c2d3cf",
  "result": {
    "engine": "knitr",
    "markdown": "# Transiciones {#MatricesT}\n\nPor: Aucencia Emeterio-Lara, Ernesto Mujíca, Elaine González y Raymond L. Tremblay\n\nLas transiciones describen los cambios individuales entre estados\ndemográficos —como supervivencia, crecimiento y regresión— que conectan\nel ciclo de vida con la dinámica poblacional. Este capítulo introduce el\nconcepto de transiciones como los procesos fundamentales que determinan\nla estructura y evolución de una población a lo largo del tiempo.\n\n## Transiciones demográficas y construcción del ciclo de vida poblacional\n\nLas transiciones representan los procesos mediante los cuales los individuos\ncambian de estado entre intervalos de tiempo, ya sea permaneciendo en el\nmismo estadio, creciendo a uno nuevo, retrocediendo o contribuyendo a la\npoblación a través de la reproducción. En los modelos de proyección\npoblacional, estas transiciones constituyen los elementos básicos de la\nmatriz, conectando las tasas vitales individuales con la dinámica\npoblacional a nivel agregado.\n\nEn este capítulo se analizan las transiciones como componentes explícitos\ndel ciclo de vida, mostrando cómo su definición y parametrización influyen\ndirectamente en la estructura de la matriz de proyección y en la dinámica\nresultante. Se discute cómo diferentes formulaciones de las transiciones\nreflejan supuestos biológicos distintos, tales como crecimiento continuo\nversus discreto, estasis, o la incorporación de retrocesos ontogenéticos.\n\nA diferencia de los capítulos sobre crecimiento poblacional o propiedades\nmatriciales, este capítulo se centra en el nivel **causal** de la dinámica\ndemográfica: los procesos que generan los patrones observados de\ncrecimiento, estabilidad o declive. Comprender las transiciones es esencial\npara interpretar análisis posteriores de sensibilidad, elasticidad,\nproyecciones poblacionales y modelos bayesianos, ya que cualquier cambio en\nestas métricas surge directamente de modificaciones en las transiciones\nsubyacentes.\n\n#### Librerías de R requeridas para el siguiente módulo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(gt)\nlibrary(popbio)\nlibrary(Rcompadre)\nlibrary(DiagrammeR)\n```\n:::\n\n\n## Introducción\n\nEn este capítulo se explica cómo calcular las transiciones para la matriz de Lefkovitch (transiciones por etapas). La primera parte aborda el cálculo tradicional a mano, mientras que la segunda muestra cómo realizarlo de manera más eficiente utilizando funciones disponibles en paquetes de R.\n\nLos métodos presentados son una adaptación de los propuestos por [@caswell2000matrix] y se incluye una aplicación en orquídeas [@tremblay2003population]. Si ya has realizado análisis de matrices de transición, probablemente conozcas el método tradicional y podrías omitir esta sección. Este procedimiento consiste en calcular las proporciones de individuos que transitan de una clase de edad o etapa a otra, pero hacerlo manualmente puede ser tedioso y propenso a errores. Aun así, es recomendable realizarlo al menos una vez para comprender la mecánica del cálculo.\n\nEn la segunda parte del capítulo se muestra cómo calcular las transiciones utilizando la función projection.matrix del paquete popbio, una alternativa más eficiente y menos susceptible a errores que el método manual.\n\n## Definición y parametrización de transiciones\n\nA continuación se describen los distintos tipos de transiciones y su\nimplementación en modelos de proyección poblacional.\n\nLas transiciones definen las propiedades estructurales de la matriz,\ndiscutidas en el capítulo sobre\npropiedades poblacionales. La importancia relativa de cada transición se evalúa más adelante mediante\nel análisis de elasticidad poblacional.\n\n------------------------------------------------------------------------\n\n## Métodos tradicionales de calcular las transiciones\n\nEl primer paso consiste en construir una tabla de datos con los individuos muestreados en dos periodos de tiempo (por ejemplo, con un intervalo de un año). Supongamos que tenemos 19 individuos de una orquídea con cuatro estados:\n\n-   Plantas pequeñas\n-   Juveniles\n-   Adultos\n-   Muerto\n\nEn el primer periodo:\n\n-   7 individuos estaban en plantas pequeñas\n-   6 en juveniles\n-   6 en adultos\n\nPara calcular las transiciones, debemos obtener la proporción de individuos que pasan de un estado a otro. Por ejemplo, de los 7 individuos que eran plantas pequeñas en el primer periodo:\n\n-   1 permaneció como planta pequeña\n-   2 pasaron a juveniles\n-   3 pasaron a adultos\n-   1 murió\n\nEsto se traduce en las siguientes proporciones:\n\n-   Plantas pequeñas → Plantas pequeñas: $\\frac{1}{7}$ = 0.142871\n-   Plantas pequeñas → Juveniles: $\\frac{2}{7}$ = 0.285772\n-   Plantas pequeñas → Adultos: $\\frac{3}{7}$ = 0.428573\n-   Plantas pequeñas → Muerto: $\\frac{1}{7}$ = 0.142871\n\nLa suma de estas proporciones debe ser igual a 1 (o muy cercana, considerando redondeos).\n\n\n::: {.cell}\n\n```{.r .cell-code}\na=1/7\nb=2/7\nc=3/7\nd=1/7\n\nsum=a+b+c+d\nsum\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\nLa suma de la proporciones calculado de las proporciones\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum2=0.1428+0.2857+0.4285+0.1428\nsum2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9998\n```\n\n\n:::\n:::\n\n\n**Nota**: La suma de todas las transiciones debe ser exactamente 1.000. No puede ser mayor ni menor que 1. Si la suma es distinta de 1, significa que hay un error en el cálculo de las proporciones. Una causa frecuente de este problema es el redondeo excesivo o incorrecto. En este caso, la suma total es 0.9998, lo cual es suficientemente cercano a 1.0.\n\nAhora calculamos las otras transiciones de juveniles a otras clases\n\n-   0/6 = 0.0000, transitaron de \"juveniles\" a \"plantas pequeñas\"\n-   3/6 = 0.5000, transitaron de \"juveniles\" a \"juveniles\"\n-   2/6 = 0.3333, transitaron de \"juveniles\" a \"adultos\" '\n-   1/6 = 0.1666, murieron entre el primer y segundo periodo\n\nDe adultos a otras clases\n\n-   0/6 = 0, transitaron de \"adulto\" a \"plantas pequeñas\"\n-   0/6 = 0, transitaron de \"adulto\" a \"juveniles\"\n-   4/6 = 0.6667, transitaron de \"adulto\" a \"adulto\"\n-   2/6 = 0.3333, murieron antes del segundo periodo\n\nAquí la lista completa de las transiciones a todas las etapas posibles.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yyenrnriry\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yyenrnriry table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yyenrnriry thead, #yyenrnriry tbody, #yyenrnriry tfoot, #yyenrnriry tr, #yyenrnriry td, #yyenrnriry th {\n  border-style: none;\n}\n\n#yyenrnriry p {\n  margin: 0;\n  padding: 0;\n}\n\n#yyenrnriry .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yyenrnriry .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yyenrnriry .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yyenrnriry .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yyenrnriry .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yyenrnriry .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yyenrnriry .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yyenrnriry .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yyenrnriry .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yyenrnriry .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yyenrnriry .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yyenrnriry .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yyenrnriry .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yyenrnriry .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yyenrnriry .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yyenrnriry .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yyenrnriry .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yyenrnriry .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yyenrnriry .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yyenrnriry .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yyenrnriry .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yyenrnriry .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yyenrnriry .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yyenrnriry .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yyenrnriry .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yyenrnriry .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yyenrnriry .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yyenrnriry .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yyenrnriry .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yyenrnriry .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yyenrnriry .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yyenrnriry .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yyenrnriry .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yyenrnriry .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yyenrnriry .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yyenrnriry .gt_left {\n  text-align: left;\n}\n\n#yyenrnriry .gt_center {\n  text-align: center;\n}\n\n#yyenrnriry .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yyenrnriry .gt_font_normal {\n  font-weight: normal;\n}\n\n#yyenrnriry .gt_font_bold {\n  font-weight: bold;\n}\n\n#yyenrnriry .gt_font_italic {\n  font-style: italic;\n}\n\n#yyenrnriry .gt_super {\n  font-size: 65%;\n}\n\n#yyenrnriry .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yyenrnriry .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yyenrnriry .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yyenrnriry .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yyenrnriry .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yyenrnriry .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yyenrnriry .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#yyenrnriry .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#yyenrnriry div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Num_ind\">Num_ind</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"anio_1\">anio_1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"anio_2\">anio_2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"transición\">transición</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">1</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">Muerto</td>\n<td headers=\"transición\" class=\"gt_row gt_right\">0.1428</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">2</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"transición\" class=\"gt_row gt_right\">0.1428</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">2</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"transición\" class=\"gt_row gt_right\">0.2857</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">3</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"transición\" class=\"gt_row gt_right\">0.4285</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">4</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">Muerto</td>\n<td headers=\"transición\" class=\"gt_row gt_right\">0.1666</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">4</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"transición\" class=\"gt_row gt_right\">0.0000</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">5</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"transición\" class=\"gt_row gt_right\">0.5000</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">6</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"transición\" class=\"gt_row gt_right\">0.3333</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">7</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">Muerto</td>\n<td headers=\"transición\" class=\"gt_row gt_right\">0.3333</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">7</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"transición\" class=\"gt_row gt_right\">0.0000</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">8</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"transición\" class=\"gt_row gt_right\">0.0000</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">9</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"transición\" class=\"gt_row gt_right\">0.6777</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Construcción de la matriz de transiciones\n\nAhora utilizamos los valores calculados anteriormente para construir la matriz de transiciones.\n\n**Importante**:\n\n-   Las columnas representan el estado en el primer periodo.\n-   Las filas representan el estado en el segundo periodo.\n\nLas transiciones hacia el estado “Muerto” no se incluyen en la matriz, ya que los análisis reconocen automáticamente que la proporción de mortalidad se obtiene como:\n\n$$Proporción-de-fallecimiento = 1 − suma-de-las-transiciones-en-la-fila$$\n\nPara crear la matriz en `R`, se utiliza la función *matrix()*, que incluye los siguientes argumentos:\n\n-   nrow = número de filas (y columnas, porque la matriz siempre será cuadrada).\n-   byrow = indica si los datos se llenan por filas (TRUE) o por columnas (FALSE).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nficticia_matrix=matrix(c(0.1428, 0.0000, 0.0000,\n                         0.2857, 0.5000, 0.0000,\n                         0.4285, 0.3333, 0.6777), nrow=3, byrow=TRUE)\n\nficticia_matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       [,1]   [,2]   [,3]\n[1,] 0.1428 0.0000 0.0000\n[2,] 0.2857 0.5000 0.0000\n[3,] 0.4285 0.3333 0.6777\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Incorporación de los nombres de las etapas\n\nEs una buena práctica asignar nombres a las filas y columnas de la matriz, ya que esto facilita la interpretación y ayuda a detectar inconsistencias o posibles errores.\n\nPara ello, se utilizan dos funciones en R:\n\n-   rownames(): asigna nombres a las filas.\n-   colnames(): asigna nombres a las columnas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrownames(ficticia_matrix)<-c(\"plantas_pequeñas\", \"juvenil\", \"adulto\")\ncolnames(ficticia_matrix)<-c(\"plantas_pequeñas\", \"juvenil\", \"adulto\")\n\nficticia_matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 plantas_pequeñas juvenil adulto\nplantas_pequeñas           0.1428  0.0000 0.0000\njuvenil                    0.2857  0.5000 0.0000\nadulto                     0.4285  0.3333 0.6777\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Construcción de la matriz con funciones en R\n\nEn la siguiente sección aprenderemos a calcular las transiciones de manera más eficiente utilizando funciones disponibles en un paquete de R. La función principal que emplearemos es `projection.matrix` del paquete `popbio`.\n\nEsta función es mucho más rápida y menos propensa a errores que realizar los cálculos manualmente. En investigaciones reales, la cantidad de datos suele ser mucho mayor que en el ejemplo anterior, y a mayor volumen de datos, mayor es la probabilidad de cometer errores si se calculan las transiciones a mano.\n\nLa función `projection.matrix` permite calcular tanto las transiciones como la fecundidad a partir de una tabla que contiene los estados de los individuos en dos periodos de tiempo. Esto la convierte en una herramienta muy útil para obtener resultados precisos y eficientes.\n\nLos principales argumentos de la función `projection.matrix` son los siguientes:\n\n```         \nprojection.matrix(\n  transitions, # el nombre de la tabla de datos con los estados de los individuos en dos periodos de tiempo\n  stage = NULL, # el nombre de la columna con los estados en el primer tiempo\n  fate = NULL, # el nombre de la column con los estados en el segundo tiempo\n  fertility = NULL, la información sobre la fertilidad\n  sort = NULL, # si se quiere ordenar los estados de la historia de vida\n  add = NULL,\n  stages = NULL, # los nombres de las etapas del modelo en el primer y el segundo muestreo\n  TF = FALSE # si quiere que la matriz de transiciones y de fertilidad sean separados usa = TRUE \n   )\n```\n\n## Salida de la función projection.matrix\n\nEl output de la función `projection.matrix` es una lista que contiene dos matrices:\n\n-   **T**: incluye únicamente los valores de transición entre etapas.\n-   **F**: incluye únicamente los valores de fertilidad, es decir, la cantidad de individuos que se incorporan a cada clase de edad por reproducción no clonal.\n\n## Preparación de los datos antes del análisis\n\nAntes de comenzar con los análisis, es importante renombrar las columnas para evitar problemas con la función projection.matrix. En este caso:\n\n-   Cambiamos anio_1 a stage.\n-   Cambiamos anio_2 a fate.\n\nEstos nombres corresponden a las etapas en el primer y segundo periodo de tiempo. El término fate se traduce al español como “destino”.\n\nLos datos deben estar organizados en formato de tabla, donde:\n\n-   Cada fila representa un individuo.\n-   Cada columna representa una variable.\n\nEn nuestro ejemplo, la tabla contiene 19 filas y 4 columnas. La columna “transición” no es necesaria para la función `projection.matrix`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gt)\nOrchis_ficticia_por_ind=tribble(~Num_ind, ~anio_1, ~anio_2, ~fertilidad,\n                        1,  \"plantas_pequeñas\", \"Muerto\",  0,\n                        2,  \"plantas_pequeñas\", \"plantas_pequeñas\",0,\n                        3,  \"plantas_pequeñas\", \"juvenil\",0,\n                        4,  \"plantas_pequeñas\", \"juvenil\",0,\n                        5,  \"plantas_pequeñas\", \"adulto\",0,\n                        6,  \"plantas_pequeñas\", \"adulto\",0,\n                        7,  \"plantas_pequeñas\", \"adulto\",0,\n                        8,  \"juvenil\", \"Muerto\",0,\n                        9,  \"juvenil\", \"juvenil\",0,\n                        10, \"juvenil\", \"juvenil\",0,\n                        11, \"juvenil\", \"juvenil\",0,\n                        12, \"juvenil\", \"adulto\",0,\n                        13, \"juvenil\", \"adulto\",0,\n                        14, \"adulto\", \"Muerto\",0,\n                        15, \"adulto\", \"Muerto\",0 ,\n                        16, \"adulto\", \"adulto\",0,\n                        17, \"adulto\", \"adulto\",1,\n                        18, \"adulto\", \"adulto\",0,\n                        19, \"adulto\", \"adulto\",0\n                        )\ngt(Orchis_ficticia_por_ind) \n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"tqfiirvqmv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tqfiirvqmv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tqfiirvqmv thead, #tqfiirvqmv tbody, #tqfiirvqmv tfoot, #tqfiirvqmv tr, #tqfiirvqmv td, #tqfiirvqmv th {\n  border-style: none;\n}\n\n#tqfiirvqmv p {\n  margin: 0;\n  padding: 0;\n}\n\n#tqfiirvqmv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tqfiirvqmv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tqfiirvqmv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tqfiirvqmv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tqfiirvqmv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tqfiirvqmv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tqfiirvqmv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tqfiirvqmv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tqfiirvqmv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tqfiirvqmv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tqfiirvqmv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tqfiirvqmv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tqfiirvqmv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tqfiirvqmv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tqfiirvqmv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tqfiirvqmv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tqfiirvqmv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tqfiirvqmv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tqfiirvqmv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tqfiirvqmv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tqfiirvqmv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tqfiirvqmv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tqfiirvqmv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tqfiirvqmv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tqfiirvqmv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tqfiirvqmv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tqfiirvqmv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tqfiirvqmv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tqfiirvqmv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tqfiirvqmv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tqfiirvqmv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tqfiirvqmv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tqfiirvqmv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tqfiirvqmv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tqfiirvqmv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tqfiirvqmv .gt_left {\n  text-align: left;\n}\n\n#tqfiirvqmv .gt_center {\n  text-align: center;\n}\n\n#tqfiirvqmv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tqfiirvqmv .gt_font_normal {\n  font-weight: normal;\n}\n\n#tqfiirvqmv .gt_font_bold {\n  font-weight: bold;\n}\n\n#tqfiirvqmv .gt_font_italic {\n  font-style: italic;\n}\n\n#tqfiirvqmv .gt_super {\n  font-size: 65%;\n}\n\n#tqfiirvqmv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tqfiirvqmv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tqfiirvqmv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tqfiirvqmv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tqfiirvqmv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tqfiirvqmv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tqfiirvqmv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#tqfiirvqmv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#tqfiirvqmv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Num_ind\">Num_ind</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"anio_1\">anio_1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"anio_2\">anio_2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"fertilidad\">fertilidad</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">1</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">Muerto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">2</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">3</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">4</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">5</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">6</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">7</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">8</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">Muerto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">9</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">10</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">11</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">12</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">13</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">14</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">Muerto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">15</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">Muerto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">16</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">17</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">18</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">19</td>\n<td headers=\"anio_1\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"anio_2\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nA continuación, mostramos cómo cambiar los nombres de las columnas a **stage** y **fate**, y luego visualizar los primeros seis individuos de la tabla de datos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nOrchis_ficticia_por_ind=Orchis_ficticia_por_ind %>% rename(stage=anio_1, fate=anio_2)\n\ngt(head(Orchis_ficticia_por_ind))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"biijdhwqdj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#biijdhwqdj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#biijdhwqdj thead, #biijdhwqdj tbody, #biijdhwqdj tfoot, #biijdhwqdj tr, #biijdhwqdj td, #biijdhwqdj th {\n  border-style: none;\n}\n\n#biijdhwqdj p {\n  margin: 0;\n  padding: 0;\n}\n\n#biijdhwqdj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#biijdhwqdj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#biijdhwqdj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#biijdhwqdj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#biijdhwqdj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#biijdhwqdj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#biijdhwqdj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#biijdhwqdj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#biijdhwqdj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#biijdhwqdj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#biijdhwqdj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#biijdhwqdj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#biijdhwqdj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#biijdhwqdj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#biijdhwqdj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#biijdhwqdj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#biijdhwqdj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#biijdhwqdj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#biijdhwqdj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#biijdhwqdj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#biijdhwqdj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#biijdhwqdj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#biijdhwqdj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#biijdhwqdj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#biijdhwqdj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#biijdhwqdj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#biijdhwqdj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#biijdhwqdj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#biijdhwqdj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#biijdhwqdj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#biijdhwqdj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#biijdhwqdj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#biijdhwqdj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#biijdhwqdj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#biijdhwqdj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#biijdhwqdj .gt_left {\n  text-align: left;\n}\n\n#biijdhwqdj .gt_center {\n  text-align: center;\n}\n\n#biijdhwqdj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#biijdhwqdj .gt_font_normal {\n  font-weight: normal;\n}\n\n#biijdhwqdj .gt_font_bold {\n  font-weight: bold;\n}\n\n#biijdhwqdj .gt_font_italic {\n  font-style: italic;\n}\n\n#biijdhwqdj .gt_super {\n  font-size: 65%;\n}\n\n#biijdhwqdj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#biijdhwqdj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#biijdhwqdj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#biijdhwqdj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#biijdhwqdj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#biijdhwqdj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#biijdhwqdj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#biijdhwqdj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#biijdhwqdj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Num_ind\">Num_ind</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stage\">stage</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"fate\">fate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"fertilidad\">fertilidad</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stage\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"fate\" class=\"gt_row gt_left\">Muerto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">2</td>\n<td headers=\"stage\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"fate\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">3</td>\n<td headers=\"stage\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"fate\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">4</td>\n<td headers=\"stage\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"fate\" class=\"gt_row gt_left\">juvenil</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">5</td>\n<td headers=\"stage\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"fate\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Num_ind\" class=\"gt_row gt_right\">6</td>\n<td headers=\"stage\" class=\"gt_row gt_left\">plantas_pequeñas</td>\n<td headers=\"fate\" class=\"gt_row gt_left\">adulto</td>\n<td headers=\"fertilidad\" class=\"gt_row gt_right\">0</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nUna vez que hemos asignado los nombres a las columnas, podemos utilizar la función projection.matrix para calcular las transiciones y la fertilidad.\n\nEn este contexto, la columna “fertilidad” representa la cantidad de individuos que se incorporan a cada clase de edad en el siguiente periodo.\n\nEn nuestro caso, solo los adultos pueden reproducirse, añadiendo nuevos individuos a la clase “plantas pequeñas”. La fertilidad se calcula como:\n\nFertilidad=$\\frac{1}{6}$ = 0.1666\n\nEsto significa que, en promedio, cada adulto añade un nuevo individuo a la clase “plantas pequeñas” en el segundo periodo de tiempo.\n\nAquí un ejemplo de la función\n\nprojection.matrix(Orchis_ficticia_df, stage, fate, fertilidad, stages, TF=TRUE)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nOrchis_ficticia_df = as.data.frame(Orchis_ficticia_por_ind) # Nota que es importante convertir la tabla de datos a un data frame si es en formato de tibble.\n\nstages = c(\"plantas_pequeñas\", \"juvenil\", \"adulto\") # Las etapas del modelo en el primer muestreo\n\nfate = c(\"plantas_pequeñas\", \"juvenil\", \"adulto\", \"Muerto\") # Las etapas del modelo en el segundo periodo de muestreo\n\nprojection.matrix(Orchis_ficticia_df, stage, fate, fertilidad, stages, TF=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$T\n                  \n                   plantas_pequeñas   juvenil    adulto\n  plantas_pequeñas        0.1428571 0.0000000 0.0000000\n  juvenil                 0.2857143 0.5000000 0.0000000\n  adulto                  0.4285714 0.3333333 0.6666667\n\n$F\n                  \n                   plantas_pequeñas   juvenil    adulto\n  plantas_pequeñas        0.0000000 0.0000000 0.1666667\n  juvenil                 0.0000000 0.0000000 0.0000000\n  adulto                  0.0000000 0.0000000 0.0000000\n```\n\n\n:::\n:::\n\n\n## Unión de matrices\n\nSi deseas obtener una matriz que combine tanto las transiciones como la fertilidad, puedes utilizar el argumento **TF** = FALSE en relación con **matA**.\n\nEn este caso, la matriz resultante se define como:\n\n$$matA= \\text{matT} + \\text{matF}$$ donde:\n\n-   matT es la matriz de transiciones.\n-   matF es la matriz de fertilidad.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprojection.matrix(Orchis_ficticia_df, stage, fate, fertilidad, stages, TF=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  \n                   plantas_pequeñas   juvenil    adulto\n  plantas_pequeñas        0.1428571 0.0000000 0.1666667\n  juvenil                 0.2857143 0.5000000 0.0000000\n  adulto                  0.4285714 0.3333333 0.6666667\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Matriz de Clonaje\n\nMuchas orquídeas se reproducen por clonación, lo que significa que los individuos son genéticamente idénticos y se originan a partir de la planta madre. En algunos casos, estos clones se separan mediante un keiki o por división de los rizomas cuando estos se deterioran o mueren. Este es un método de reproducción asexual.\n\nEn este contexto, la matriz de transiciones puede modificarse para incluir el clonaje. Existen pocos ejemplos en orquídeas donde se incorpora una submatriz de clonaje, denominada matC. Desde el punto de vista evolutivo, este proceso representa el crecimiento de un individuo y no debe considerarse como fecundidad, ya que es un mecanismo distinto. Este concepto de crecimiento es relevante en los análisis de selección natural y deriva genética, dos procesos evolutivos fundamentales. Además, la reproducción asexual puede influir en el crecimiento intrínseco y la dinámica poblacional.\n\nComo ejemplo, revisamos el trabajo sobre *Cypripedium calceolus* en Europa [@garcia2010living]. En este estudio, los autores analizaron la dinámica de poblaciones situadas en la periferia de su distribución geográfica, específicamente en los Pirineos y el norte de Europa. Aprovecharemos este caso para mostrar cómo se identifican especies que incluyen una matriz de clonaje (**matC**).\n\nEl primer paso consiste en descargar los datos desde la base de datos COMPADRE utilizando la función `cdb_fetch` del paquete **Rcompadre**. Esta función obtiene la información y la almacena en un objeto llamado compadre.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompadre <- readRDS(\"data/COMPADRE_2026.rds\") # Usar este código para bajar los datos del repositorio de COMPADRE. Tiene que haber activado la librería de Rcompadre.\n```\n:::\n\n\n------------------------------------------------------------------------\n\n### Extracción de COMPADRE las matrices *Cypripedium calceolus*.\n\nSegundo extraer de la base de datos de COMPADRE las matrices de transiciones de *Cypripedium calceolus* del artículo mencionado arriba.\n\nLos pasos son los siguientes\n\n-   Filtrar la base de datos para *Cypripedium calceolus*\n-   Filtrar la base de datos para el DOI del artículo\n-   Filtrar la base de datos para la dimensión de la matriz de transiciones (6x6)\n-   Filtrar la base base de datos para una matriz en particular (242623)\n\nNOTA que se podría haber filtrado parte la **MatrixID** solamente si uno conoce la identificación de esta matriz en la base de datos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCyp_cal_matC = compadre %>%\n  select(MatrixID, SpeciesAccepted, mat, Authors, DOI_ISBN, MatrixDimension) %>%\n  filter(\n    SpeciesAccepted %in% c(\"Cypripedium calceolus\"),\n    DOI_ISBN %in% c(\"10.1111/j.1523-1739.2010.01466.x\"),\n    MatrixDimension %in% c(6),\n    MatrixID %in% c(242623)\n  ) # filtrar la base de datos para la matriz de interés\n  \n\n#Cyp_cal_matC$mat # para el año 2000 a 2001\n```\n:::\n\n\n### matA de *Cypripedium calceolus*, MatrixID = 242623\n\nLas matriz de transiciones de *Cypripedium calceolus* tiene una matriz de transiciones de fecundidad y de clonaje, matA=matU+matF+matC\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmatA <- matA(Cyp_cal_matC) # extraer la matriz a partir de la base de datos de COMPADRE\nmatcc=as.matrix(as.data.frame(matA)) # convertir la matriz a un data frame y luego a un objeto en forma de matriz \nmatcc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     A1   A2   A3   A4   A5   A6\nA1 0.11 0.10 0.22 0.14 0.22 0.17\nA2 0.17 0.52 0.02 0.01 0.02 0.03\nA3 0.31 0.19 0.47 0.20 0.05 0.07\nA4 0.11 0.10 0.16 0.35 0.13 0.09\nA5 0.31 0.00 0.04 0.22 0.57 0.41\nA6 0.00 0.00 0.00 0.00 0.00 0.27\n```\n\n\n:::\n:::\n\n\n## Extracción de la matriz de Clonaje\n\nNOTE que la matriz de clonaje es la siguiente.\n\nLo que se observa es que hay NUEVOS INDIVIDUOS en el tiempo $\\text{t}_{i+1}$, que provienen de los individuos en el tiempo $\\text{t}_i$. En este caso, son individuos de provienen de a las etapas 4, 5 y 6 que producen individuos nuevos (por clonaje) en la etapa 3 y 4.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmatC <- matC(Cyp_cal_matC) # extraer la matriz de clonaje a partir de la base de datos de COMPADRE\nmatC\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n   C1 C2 C3  C4   C5   C6\nC1  0  0  0 0.0 0.00 0.00\nC2  0  0  0 0.0 0.00 0.00\nC3  0  0  0 0.2 0.05 0.07\nC4  0  0  0 0.0 0.00 0.09\nC5  0  0  0 0.0 0.00 0.00\nC6  0  0  0 0.0 0.00 0.00\n```\n\n\n:::\n:::\n\n\n### El ciclo de vida de *Cypripedium calceolus* con clonaje\n\nAhora vemos el ciclo de vida de *Cypripedium calceolus* en este estudio donde las lineas azules son las transiciones de una etapa a otra por clonaje.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#etapas <- c(\"A1\", \"A2\", \"A3\", \"A4\", \"A5\", \"A6\")\netapas <- c(\"Dormant\", \"Smallest\", \"Small\", \"Intermediate\", \"Large\", \"Extra Large\") # Etapas del articulo\n\netapas <- factor(etapas, levels =  c(\"Dormant\", \"Smallest\", \"Small\", \"Intermediate\", \"Large\", \"Extra Large\"))\ntitle <- NULL\ngraph <- expand.grid(to = etapas, from = etapas)\ngraph$trans <- round(c(matcc), 2)\ngraph <- graph[graph$trans > 0, ]\nnodes <- paste(paste0(\"'\", etapas, \"'\"), collapse = \"; \")\ngraph$min_len <- (as.numeric(graph$to) - as.numeric(graph$from)) * 3\ngraph$col <- c(\"red\",   \"black\", \"black\", \"black\",\"black\",\n               \"black\", \"red\",   \"black\", \"black\",\n               \"black\", \"black\", \"red\",   \"black\", \"black\",\n               \"black\", \"black\", \"blue\",  \"black\", \"black\",\n               \"black\", \"black\", \"blue\",  \"black\", \"black\", \n               \"black\", \"black\", \"blue\",  \"blue\",  \"black\", \"black\"\n)\nedges <- paste0(\"'\", graph$from, \"'\", \" -> \", \"'\", graph$to, \"'\",\n  \"[minlen=\", graph$min_len,\n  \",fontsize=\", 10,\n  \",color=\", graph$col,\n  \",xlabel=\", paste(\"\\\"\", graph$trans),\n  \"\\\"]\\n\",\n  collapse = \"\"\n)\ngrViz(\n  paste(\n    \"\ndigraph {\n  {\n    graph[overlap=false];\n    rank=etapas;\n    node [shape=\", \"egg\", \", fontsize=\", 12, \"];\",\n    nodes, \"\n  }\",\n    \"ordering=out\n  x [style=invis]\n  x -> {\", nodes, \"} [style=invis]\", edges,\n    \"labelloc=\\\"t\\\";\n  label=\\\"\", title, \"\\\"\n}\"\n  )\n) \n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"grViz html-widget html-fill-item\" id=\"htmlwidget-12505c5174c1de9219ac\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-12505c5174c1de9219ac\">{\"x\":{\"diagram\":\"\\ndigraph {\\n  {\\n    graph[overlap=false];\\n    rank=etapas;\\n    node [shape= egg , fontsize= 12 ]; \\\"Dormant\\\"; \\\"Smallest\\\"; \\\"Small\\\"; \\\"Intermediate\\\"; \\\"Large\\\"; \\\"Extra Large\\\" \\n  } ordering=out\\n  x [style=invis]\\n  x -> { \\\"Dormant\\\"; \\\"Smallest\\\"; \\\"Small\\\"; \\\"Intermediate\\\"; \\\"Large\\\"; \\\"Extra Large\\\" } [style=invis] \\\"Dormant\\\" -> \\\"Dormant\\\"[minlen=0,fontsize=10,color=red,xlabel=\\\" 0.11\\\"]\\n\\\"Dormant\\\" -> \\\"Smallest\\\"[minlen=3,fontsize=10,color=black,xlabel=\\\" 0.17\\\"]\\n\\\"Dormant\\\" -> \\\"Small\\\"[minlen=6,fontsize=10,color=black,xlabel=\\\" 0.31\\\"]\\n\\\"Dormant\\\" -> \\\"Intermediate\\\"[minlen=9,fontsize=10,color=black,xlabel=\\\" 0.11\\\"]\\n\\\"Dormant\\\" -> \\\"Large\\\"[minlen=12,fontsize=10,color=black,xlabel=\\\" 0.31\\\"]\\n\\\"Smallest\\\" -> \\\"Dormant\\\"[minlen=-3,fontsize=10,color=black,xlabel=\\\" 0.1\\\"]\\n\\\"Smallest\\\" -> \\\"Smallest\\\"[minlen=0,fontsize=10,color=red,xlabel=\\\" 0.52\\\"]\\n\\\"Smallest\\\" -> \\\"Small\\\"[minlen=3,fontsize=10,color=black,xlabel=\\\" 0.19\\\"]\\n\\\"Smallest\\\" -> \\\"Intermediate\\\"[minlen=6,fontsize=10,color=black,xlabel=\\\" 0.1\\\"]\\n\\\"Small\\\" -> \\\"Dormant\\\"[minlen=-6,fontsize=10,color=black,xlabel=\\\" 0.22\\\"]\\n\\\"Small\\\" -> \\\"Smallest\\\"[minlen=-3,fontsize=10,color=black,xlabel=\\\" 0.02\\\"]\\n\\\"Small\\\" -> \\\"Small\\\"[minlen=0,fontsize=10,color=red,xlabel=\\\" 0.47\\\"]\\n\\\"Small\\\" -> \\\"Intermediate\\\"[minlen=3,fontsize=10,color=black,xlabel=\\\" 0.16\\\"]\\n\\\"Small\\\" -> \\\"Large\\\"[minlen=6,fontsize=10,color=black,xlabel=\\\" 0.04\\\"]\\n\\\"Intermediate\\\" -> \\\"Dormant\\\"[minlen=-9,fontsize=10,color=black,xlabel=\\\" 0.14\\\"]\\n\\\"Intermediate\\\" -> \\\"Smallest\\\"[minlen=-6,fontsize=10,color=black,xlabel=\\\" 0.01\\\"]\\n\\\"Intermediate\\\" -> \\\"Small\\\"[minlen=-3,fontsize=10,color=blue,xlabel=\\\" 0.2\\\"]\\n\\\"Intermediate\\\" -> \\\"Intermediate\\\"[minlen=0,fontsize=10,color=black,xlabel=\\\" 0.35\\\"]\\n\\\"Intermediate\\\" -> \\\"Large\\\"[minlen=3,fontsize=10,color=black,xlabel=\\\" 0.22\\\"]\\n\\\"Large\\\" -> \\\"Dormant\\\"[minlen=-12,fontsize=10,color=black,xlabel=\\\" 0.22\\\"]\\n\\\"Large\\\" -> \\\"Smallest\\\"[minlen=-9,fontsize=10,color=black,xlabel=\\\" 0.02\\\"]\\n\\\"Large\\\" -> \\\"Small\\\"[minlen=-6,fontsize=10,color=blue,xlabel=\\\" 0.05\\\"]\\n\\\"Large\\\" -> \\\"Intermediate\\\"[minlen=-3,fontsize=10,color=black,xlabel=\\\" 0.13\\\"]\\n\\\"Large\\\" -> \\\"Large\\\"[minlen=0,fontsize=10,color=black,xlabel=\\\" 0.57\\\"]\\n\\\"Extra Large\\\" -> \\\"Dormant\\\"[minlen=-15,fontsize=10,color=black,xlabel=\\\" 0.17\\\"]\\n\\\"Extra Large\\\" -> \\\"Smallest\\\"[minlen=-12,fontsize=10,color=black,xlabel=\\\" 0.03\\\"]\\n\\\"Extra Large\\\" -> \\\"Small\\\"[minlen=-9,fontsize=10,color=blue,xlabel=\\\" 0.07\\\"]\\n\\\"Extra Large\\\" -> \\\"Intermediate\\\"[minlen=-6,fontsize=10,color=blue,xlabel=\\\" 0.09\\\"]\\n\\\"Extra Large\\\" -> \\\"Large\\\"[minlen=-3,fontsize=10,color=black,xlabel=\\\" 0.41\\\"]\\n\\\"Extra Large\\\" -> \\\"Extra Large\\\"[minlen=0,fontsize=10,color=black,xlabel=\\\" 0.27\\\"]\\n labelloc=\\\"t\\\";\\n  label=\\\"  \\\"\\n}\",\"config\":{\"engine\":\"dot\",\"options\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nLos estudios sobre orquídeas que incorporan matrices de clonaje son poco frecuentes, pero es fundamental considerar este proceso en los análisis de dinámica poblacional. El clonaje puede tener un impacto significativo tanto en la dinámica de las poblaciones como en la evolución de las especies.\n\nEn este contexto, el clonaje se entiende como una forma de reproducción asexual que puede modificar la estructura genética de la población y afectar su capacidad de adaptación frente a cambios ambientales.\n\n------------------------------------------------------------------------\n\n### Limitaciones de los métodos tradicionales\n\nEl uso de métodos tradicionales, ya sea mediante cálculos manuales o utilizando la función `projection.matrix` del paquete popbio, puede resultar problemático. Las dificultades surgen principalmente por condiciones de muestreo, especialmente cuando el tamaño de muestra es pequeño o cuando las transiciones son naturalmente raras [@tremblay2021population; @gascoigne2023standard], situación común en especies poco frecuentes.\n\nEn el capítulo **Impacto de datos sin sentido biológico** se analizan los problemas que ocurren cuando los datos carecen de coherencia biológica, cómo construir matrices más confiables y cuándo es apropiado emplear el método bayesiano en los análisis. Este enfoque permite resolver inconsistencias y garantizar que las matrices sean más compatibles con la biología de la especie estudiada, aumentando así la relevancia de los resultados.\n\nLos autores recomiendan utilizar el **método bayesiano** para el análisis de matrices de transición en la mayoría de los casos, excepto cuando el tamaño de muestra es muy grande y ninguna transición es rara. El método bayesiano es un enfoque estadístico que permite incorporar información previa y ajustar los modelos a los datos observados. Este enfoque es especialmente útil cuando se trabaja con datos escasos o transiciones poco frecuentes. Aunque su implementación puede ser más compleja, ofrece mayor flexibilidad y robustez, además de estimar la confianza en los valores de transición y fecundidad.\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"site_libs/viz-1.8.2/viz.js\"></script>\n<link href=\"site_libs/DiagrammeR-styles-0.2/styles.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/grViz-binding-1.0.11.9000/grViz.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}