<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Dinámica Poblacional de Orquídeas.">

<title>10&nbsp; Propiedades de las matrices y estimación de parámetros – Introducción a la Dinámica Poblacional de Orquídeas</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./111-Elasticidad.html" rel="next">
<link href="./109-Crecimiento_poblacional.html" rel="prev">
<link href="./favicon/Orchid_purple.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c93cdbe9a76e40f66b1ab6cc17c99f94.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-f70711160475c30c4eefa61411e73fbc.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-c93cdbe9a76e40f66b1ab6cc17c99f94.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<meta name="google-site-verification" content="sqB47_Ch7slOBSvYTr_Py8z8e57699jN-QJN7JqdvVI">
<link href="site_libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet">
<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="site_libs/viz-1.8.2/viz.js"></script>
<link href="site_libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">
<script src="site_libs/grViz-binding-1.0.11.9000/grViz.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./110-Propriedades.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Propiedades de las matrices y estimación de parámetros</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introducción a la Dinámica Poblacional de Orquídeas</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/raymondltremblay/Dinamica_Poblacional" title="Ejecutar el código" class="quarto-navigation-tool px-1" aria-label="Ejecutar el código"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción a la Dinámica Poblacional de Orquídeas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./102-Intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Diagnóstico poblacional: Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./103-Ciclos_de_Vida.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">El Ciclo de Vida</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./104-Recopilacion_datos_en_el_campo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Recopilar datos en el campo</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./105-Transiciones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Transiciones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./106-calcular_fecundidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Fecundidad</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./107-matU_matF_matC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Matrices de transición, fecundidad y reproducción clonal</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./108-Bayesian_PPM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estimados bayesianos de MPP</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./109-Crecimiento_poblacional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Crecimiento Poblacional</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./110-Propriedades.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Propiedades de las matrices y estimación de parámetros</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./111-Elasticidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Elasticidad y Sensibilidad</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./112-Dinamica_de_Transiciones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Dinámica transitoria</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./113-Funciones_de_Transferencia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Funciones de Transferencias</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./114-LTRE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Experimento de Respuesta de Tabla de Vida</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./115-Metodos_de_simulaciones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Variación Temporal y Espacial</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./116-Estudio_evolutivo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">El uso de matrices para estudios evolutivos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./119-COMPADRE_ORCHIDS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">COMPADRE y Orquídeas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./120-Rage_orquideas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Rage y Orquídeas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./121-Traduccion_protocolo_informacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Un protocolo estándar para comunicar información demográfica estructurada en fases discretas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./122-Impacto_de_Datos_sin_Sentido.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Impactos de datos sin sentido biológicos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./123-Conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Conclusión</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Historia</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./117_Historia_breve.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Historia breve de los PPM en orquídeas.</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./118-Carl_Olaf_Tamm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Carl Olaf Tamm</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Apéndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Appendix_A_Species_List.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apéndice A</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Appendix_B_Hoja_de_datos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apéndice B</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Appendix_C_Datos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apéndice C</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Agradecimientos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Agradecimiento</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#por-mariana-hernández-apolinar-y-paola-portillo-tzompa" id="toc-por-mariana-hernández-apolinar-y-paola-portillo-tzompa" class="nav-link active" data-scroll-target="#por-mariana-hernández-apolinar-y-paola-portillo-tzompa"><span class="header-section-number">10.1</span> Por: Mariana Hernández-Apolinar y Paola Portillo Tzompa</a></li>
  <li><a href="#propiedades-fundamentales-de-las-matrices-de-proyección-poblacional" id="toc-propiedades-fundamentales-de-las-matrices-de-proyección-poblacional" class="nav-link" data-scroll-target="#propiedades-fundamentales-de-las-matrices-de-proyección-poblacional"><span class="header-section-number">10.2</span> Propiedades fundamentales de las matrices de proyección poblacional</a></li>
  <li><a href="#propiedades-matemáticas-y-cálculo-computacional" id="toc-propiedades-matemáticas-y-cálculo-computacional" class="nav-link" data-scroll-target="#propiedades-matemáticas-y-cálculo-computacional"><span class="header-section-number">10.3</span> Propiedades matemáticas y cálculo computacional</a></li>
  <li><a href="#propiedades-supuestos-e-índices-matriciales" id="toc-propiedades-supuestos-e-índices-matriciales" class="nav-link" data-scroll-target="#propiedades-supuestos-e-índices-matriciales"><span class="header-section-number">10.4</span> Propiedades, supuestos e índices matriciales</a></li>
  <li><a href="#construir-una-matriz-poblacional" id="toc-construir-una-matriz-poblacional" class="nav-link" data-scroll-target="#construir-una-matriz-poblacional"><span class="header-section-number">10.5</span> Construir una matriz poblacional</a></li>
  <li><a href="#matriz-de-proyección-poblacional-mpp" id="toc-matriz-de-proyección-poblacional-mpp" class="nav-link" data-scroll-target="#matriz-de-proyección-poblacional-mpp"><span class="header-section-number">10.6</span> Matriz de proyección poblacional (MPP)</a></li>
  <li><a href="#supuestos-de-la-matriz-poblacional" id="toc-supuestos-de-la-matriz-poblacional" class="nav-link" data-scroll-target="#supuestos-de-la-matriz-poblacional"><span class="header-section-number">10.7</span> Supuestos de la matriz poblacional</a>
  <ul class="collapse">
  <li><a href="#dimensión-cuadrada" id="toc-dimensión-cuadrada" class="nav-link" data-scroll-target="#dimensión-cuadrada"><span class="header-section-number">10.7.1</span> Dimensión cuadrada</a></li>
  <li><a href="#ergócidad" id="toc-ergócidad" class="nav-link" data-scroll-target="#ergócidad"><span class="header-section-number">10.7.2</span> Ergócidad</a></li>
  <li><a href="#elementos-no-negativa" id="toc-elementos-no-negativa" class="nav-link" data-scroll-target="#elementos-no-negativa"><span class="header-section-number">10.7.3</span> Elementos no negativa</a></li>
  <li><a href="#irreducibilidad" id="toc-irreducibilidad" class="nav-link" data-scroll-target="#irreducibilidad"><span class="header-section-number">10.7.4</span> Irreducibilidad</a></li>
  <li><a href="#primitividad" id="toc-primitividad" class="nav-link" data-scroll-target="#primitividad"><span class="header-section-number">10.7.5</span> Primitividad</a></li>
  </ul></li>
  <li><a href="#índices-de-descripción-de-la-matriz-poblacional" id="toc-índices-de-descripción-de-la-matriz-poblacional" class="nav-link" data-scroll-target="#índices-de-descripción-de-la-matriz-poblacional"><span class="header-section-number">10.8</span> Índices de descripción de la matriz poblacional</a>
  <ul class="collapse">
  <li><a href="#estructura-estable" id="toc-estructura-estable" class="nav-link" data-scroll-target="#estructura-estable"><span class="header-section-number">10.8.1</span> Estructura Estable</a></li>
  <li><a href="#valor-reproductivo" id="toc-valor-reproductivo" class="nav-link" data-scroll-target="#valor-reproductivo"><span class="header-section-number">10.8.2</span> Valor reproductivo</a></li>
  <li><a href="#análisis-de-convergencia-y-amortigamiento-damping-ratio" id="toc-análisis-de-convergencia-y-amortigamiento-damping-ratio" class="nav-link" data-scroll-target="#análisis-de-convergencia-y-amortigamiento-damping-ratio"><span class="header-section-number">10.8.3</span> Análisis de Convergencia y Amortigamiento (Damping ratio)</a></li>
  <li><a href="#graficación-del-índice-de-amortiguamiento" id="toc-graficación-del-índice-de-amortiguamiento" class="nav-link" data-scroll-target="#graficación-del-índice-de-amortiguamiento"><span class="header-section-number">10.8.4</span> Graficación del Índice de amortiguamiento</a></li>
  <li><a href="#intepretación-del-gráfico-de-amortiguamiento" id="toc-intepretación-del-gráfico-de-amortiguamiento" class="nav-link" data-scroll-target="#intepretación-del-gráfico-de-amortiguamiento"><span class="header-section-number">10.8.5</span> Intepretación del gráfico de amortiguamiento</a></li>
  <li><a href="#graficación-del-tiempo-de-convergencia-al-estado-estable-de-cada-etapa-de-vida" id="toc-graficación-del-tiempo-de-convergencia-al-estado-estable-de-cada-etapa-de-vida" class="nav-link" data-scroll-target="#graficación-del-tiempo-de-convergencia-al-estado-estable-de-cada-etapa-de-vida"><span class="header-section-number">10.8.6</span> Graficación del tiempo de convergencia al estado estable de cada etapa de vida</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/raymondltremblay/Dinamica_Poblacional/edit/main/110-Propriedades.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/raymondltremblay/Dinamica_Poblacional/issues/new" class="toc-action"><i class="bi empty"></i>Informar sobre problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Propiedades de las matrices y estimación de parámetros</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="por-mariana-hernández-apolinar-y-paola-portillo-tzompa" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="por-mariana-hernández-apolinar-y-paola-portillo-tzompa"><span class="header-section-number">10.1</span> Por: Mariana Hernández-Apolinar y Paola Portillo Tzompa</h2>
<p>Las propiedades de una matriz de proyección poblacional determinan cómo se comporta una población a largo plazo bajo condiciones constantes. Este capítulo introduce las principales propiedades matemáticas y biológicas de las matrices poblacionales y explica por qué son centrales para interpretar la dinámica poblacional más allá del valor de λ.</p>
</section>
<section id="propiedades-fundamentales-de-las-matrices-de-proyección-poblacional" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="propiedades-fundamentales-de-las-matrices-de-proyección-poblacional"><span class="header-section-number">10.2</span> Propiedades fundamentales de las matrices de proyección poblacional</h2>
<p>Las matrices de proyección poblacional poseen un conjunto de propiedades matemáticas que gobiernan la dinámica demográfica de las poblaciones a largo plazo. Entre estas propiedades se encuentran la estructura estable por estadios, el valor propio dominante (λ), el vector reproductivo y la convergencia asintótica de la población hacia un patrón dinámico estable.</p>
<p>En este capítulo se examinan estas propiedades desde una perspectiva biológica, mostrando cómo emergen de la estructura del ciclo de vida y de las tasas vitales que describen supervivencia, crecimiento y fecundidad. Se explica cómo la estructura estable de la población representa la distribución proporcional de individuos entre estadios cuando la población ha alcanzado su dinámica asintótica, y por qué esta estructura es clave para interpretar proyecciones poblacionales y comparaciones entre escenarios.</p>
<p>Además, se introduce el concepto de valor reproductivo como una medida de la contribución relativa de cada estadio al crecimiento futuro de la población. Este capítulo se diferencia de los anteriores porque no se centra en el cálculo de λ ni en su sensibilidad a cambios paramétricos, sino en la comprensión de las propiedades estructurales que explican <strong>por qué</strong> las poblaciones exhiben determinados patrones de crecimiento, estabilidad o declive. Estas propiedades constituyen la base conceptual para análisis posteriores de elasticidad, LTRE y simulaciones poblacionales.</p>
</section>
<section id="propiedades-matemáticas-y-cálculo-computacional" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="propiedades-matemáticas-y-cálculo-computacional"><span class="header-section-number">10.3</span> Propiedades matemáticas y cálculo computacional</h2>
<p>A continuación se ilustran las propiedades matemáticas de las matrices de proyección poblacional y su cálculo mediante herramientas computacionales.</p>
<section id="librerías-de-r-requeridas-para-el-siguiente-módulo" class="level4" data-number="10.3.0.1">
<h4 data-number="10.3.0.1" class="anchored" data-anchor-id="librerías-de-r-requeridas-para-el-siguiente-módulo"><span class="header-section-number">10.3.0.1</span> Librerías de R requeridas para el siguiente módulo</h4>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(popdemo)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(popbio)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Rage)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
</section>
<section id="propiedades-supuestos-e-índices-matriciales" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="propiedades-supuestos-e-índices-matriciales"><span class="header-section-number">10.4</span> Propiedades, supuestos e índices matriciales</h2>
<p>En este capítulo aprenderemos sobre algunos índices que se usan con frecuencia en el análisis matricial. Estos índices nos ayudan a saber si una matriz es “buena” para trabajar y si los resultados que obtenemos son confiables.</p>
<p>El capítulo está dividido en dos partes:</p>
<ol type="1">
<li><strong>Índices sobre el estado de la matriz</strong></li>
</ol>
<p>Aquí veremos características básicas que debe cumplir una matriz para que el análisis sea válido:</p>
<ul>
<li><strong>Dimensión cuadrada</strong>: la matriz debe tener el mismo número de filas y columnas.</li>
<li><strong>Ergocidad</strong>: asegura que, con el tiempo, todas las partes del sistema se conecten.</li>
<li><strong>No negatividad</strong>: los valores de la matriz no pueden ser negativos.</li>
<li><strong>Irreducibilidad</strong>: indica que no se puede dividir la matriz en bloques independientes.</li>
<li><strong>Primitividad</strong>: garantiza que, después de varias iteraciones, la matriz se estabiliza.</li>
</ul>
<ol start="2" type="1">
<li><strong>Índices sobre el comportamiento a largo plazo</strong></li>
</ol>
<p>Estos se basan en modelos de proyección poblacional (MPP) y nos permiten entender cómo cambia la población antes y después de un disturbio:</p>
<ul>
<li><strong>Análisis de convergencia</strong>: mide si la población tiende a una estructura estable.</li>
<li><strong>Análisis de amortiguamiento</strong>: indica qué tan rápido se alcanza esa estabilidad.</li>
<li><strong>Valor reproductivo</strong>: muestra la importancia de cada clase en la reproducción futura.</li>
<li><strong>Estructura estable</strong>: describe la distribución de la población cuando todo se estabiliza.</li>
</ul>
<p>Si quieres profundizar en estos índices, te recomiendo consultar <span class="citation" data-cites="caswell2001matrix">(<a href="#ref-caswell2001matrix" role="doc-biblioref">Caswell, 2001</a>)</span> y <span class="citation" data-cites="stott2011framework">(<a href="#ref-stott2011framework" role="doc-biblioref">Stott, Townley &amp; Hodgson, 2011</a>)</span>.</p>
</section>
<section id="construir-una-matriz-poblacional" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="construir-una-matriz-poblacional"><span class="header-section-number">10.5</span> Construir una matriz poblacional</h2>
<p>El primer paso en el análisis matricial es construir una matriz de transición poblacional, la cual resume en una tabla la supervivencia,la reproducción y transiciones de los individuos en diferentes etapas o categorías de edad. Cada fila y columna de la matriz representa un estadio del ciclo de vida de la especie, y cada elemento dentro de la matriz describe la transición de un estadio a otro en un intervalo de tiempo determinado (por ejemplo, de un año a otro).</p>
</section>
<section id="matriz-de-proyección-poblacional-mpp" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="matriz-de-proyección-poblacional-mpp"><span class="header-section-number">10.6</span> Matriz de proyección poblacional (MPP)</h2>
<p>Una matriz de proyección poblacional (MPP) es una matriz cuadrada que permite describir y predecir la dinámica de una población a través del tiempo. En esta se organizan las probabilidades de transición entre categorías de tamaño o estado (plántulas, juveniles, adultos, etc.) junto con la fecundidad o reproducción de los individuos.</p>
<p>La MPP se utiliza para proyectar la estructura de una población en el futuro, a partir de su composición actual. Así, constituye la base para calcular tasas de crecimiento poblacional, estructuras estables, valores reproductivos y otros índices demográficos fundamentales.</p>
<p>A continuación se construye la matriz poblacional de <em>Lepanthes rubripetala</em>. Esta matriz se compone de cuatro estados: plántulas (PL), juveniles (J), adultos no reproductivos (NR) y adultos reproductivos (AR).</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Capturar los datos de la matriz para L. rubripetala (Tremblay et al. 2015)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>Lr1 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">0.4324</span>, <span class="dv">0</span>,      <span class="dv">0</span>,     <span class="fl">0.15</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                <span class="fl">0.3784</span>, <span class="fl">0.8459</span>, <span class="dv">0</span>,     <span class="dv">0</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                <span class="dv">0</span>,      <span class="fl">0.0034</span>, <span class="fl">0.7954</span>,<span class="fl">0.2300</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>                <span class="dv">0</span>,      <span class="fl">0.0890</span>, <span class="fl">0.1841</span>,<span class="fl">0.7510</span>), <span class="at">byrow=</span><span class="cn">TRUE</span>,<span class="at">ncol=</span><span class="dv">4</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Capturar las categorias de estado</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>estadios <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"PL"</span>, <span class="st">"J"</span>, <span class="st">"NR"</span>, <span class="st">"AR"</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(Lr1) <span class="ot">&lt;-</span> <span class="fu">rownames</span>(Lr1) <span class="ot">&lt;-</span> estadios</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener la matriz L. rubripetala</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>Lr1 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(Lr1[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, ], <span class="at">nrow =</span> <span class="dv">4</span>, <span class="at">dimnames =</span> <span class="fu">list</span>(estadios, estadios))</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>Lr1</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       PL      J     NR    AR
PL 0.4324 0.0000 0.0000 0.150
J  0.3784 0.8459 0.0000 0.000
NR 0.0000 0.0034 0.7954 0.230
AR 0.0000 0.0890 0.1841 0.751</code></pre>
</div>
</div>
<hr>
</section>
<section id="supuestos-de-la-matriz-poblacional" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="supuestos-de-la-matriz-poblacional"><span class="header-section-number">10.7</span> Supuestos de la matriz poblacional</h2>
<section id="dimensión-cuadrada" class="level3" data-number="10.7.1">
<h3 data-number="10.7.1" class="anchored" data-anchor-id="dimensión-cuadrada"><span class="header-section-number">10.7.1</span> Dimensión cuadrada</h3>
<p>Las matrices poblacionales deben tener dimensiones cuadradas, es decir, deben tener el mismo número de renglones que de columnas. Esta característica es importante porque cada columna y renglón representa una categoría de edad o un estado del ciclo de vida de la especie. Las columnas representa categoría de los individuos al inicio del estudio, mientras que los renglones su tránsito a otra después de un periodo de tiempo. Si la matriz no es cuadrada, no hay correspondencia que permita comparar el número de individuos por categoría al inicio y final de un periodo de estudio, por lo que será imposible estimar la tasa de crecimiento poblacional. En el caso de <em>L. rubripetala</em>, la matriz poblacional tiene 4 renglones y 4 columnas, por lo que cumple con la propiedad de dimensión cuadrada. Esto puede verificarse fácilmente en <em>R</em> usando la función <em>dim</em>.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(Lr1)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4 4</code></pre>
</div>
</div>
<hr>
</section>
<section id="ergócidad" class="level3" data-number="10.7.2">
<h3 data-number="10.7.2" class="anchored" data-anchor-id="ergócidad"><span class="header-section-number">10.7.2</span> Ergócidad</h3>
<p>Decimos que la propiedad de ergodicidad se cumple cuando el crecimiento asintótico predicho por matriz es independiente de la estructura poblacional inicial considerada en el estudio. En otras palabras, sin importar el estado inicial de la población, su comportamiento converge a una estructura estable y a una tasa de crecimiento constante a largo plazo. Si una matriz poblacional no es ergódica, el crecimiento poblacional depende de la estructura poblacional inicial, lo que implica que el promedio o la tasa de crecimiento poblacional no son buenos predictores del comportamiento poblacional a largo plazo <span class="citation" data-cites="mangalam2022ergodic">(<a href="#ref-mangalam2022ergodic" role="doc-biblioref">Mangalam &amp; Kelty-Stephen, 2022</a>)</span>. Para comprobar si la matriz es ergódica puede emplearse la función <em>isErgodic</em> del paquete <strong>popbio</strong> en <strong>R</strong>. Esta función da como resultado el valor lógico “TRUE” si la matriz es ergódica y “FALSE” en el caso contrario. En <em>L. rubripetala</em> se espera que la matriz sea ergódica, ya que los autores reportaron que la población alcanza tanto una estructura estable como una tasa de crecimiento constante en el tiempo <span class="citation" data-cites="tremblay2015stable">(<a href="#ref-tremblay2015stable" role="doc-biblioref">Tremblay, Raventos &amp; Ackerman, 2015</a>)</span>.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">isErgodic</span>(Lr1, <span class="at">digits=</span><span class="dv">5</span>, <span class="at">return.eigvec=</span><span class="cn">FALSE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>Una matriz no cumple la condición de ergodicidad cuando, por ejemplo, ningún individuo logra pasar del estado de plántula al juvenil ni al adulto. En este caso, la población queda “atascada” en las primeras etapas y no puede alcanzar una estructura estable. Si evaluamos esta matriz con la función <code>isErgodic</code> del paquete popbio en R, el resultado será FALSE. Esto indica que:</p>
<ul>
<li>El crecimiento poblacional depende de la estructura inicial, y</li>
<li>No se puede esperar que la población alcance una estructura estable ni una tasa de crecimiento constante a largo plazo.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Capturar los datos de la matriz para L. rubripetala (Tremblay et al. 2015)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>Lr1_No_erg <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">0.4324</span>, <span class="fl">0.</span>,      <span class="fl">0.</span>,     <span class="fl">0.150</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>               <span class="fl">0.</span>, <span class="fl">0.8459</span>, <span class="fl">0.</span>,     <span class="fl">0.</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>               <span class="fl">0.</span>,      <span class="fl">0.0034</span>, <span class="fl">0.7954</span>,<span class="fl">0.2300</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>               <span class="fl">0.</span>,      <span class="fl">0.0890</span>, <span class="fl">0.1841</span>,<span class="fl">0.7510</span>), <span class="at">byrow=</span><span class="cn">TRUE</span>,<span class="at">ncol=</span><span class="dv">4</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_life_cycle</span>(Lr1_No_erg, <span class="at">stages =</span> estadios, <span class="at">fontsize =</span> <span class="dv">8</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="grViz html-widget html-fill-item" id="htmlwidget-af59b6a620bd6103118c" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-af59b6a620bd6103118c">{"x":{"diagram":"\ndigraph {\n  {\n    graph[overlap=false];\n    rank=same;\n    node [shape= egg , fontsize= 12 ]; \"PL\" -> \"J\" -> \"NR\" -> \"AR\" [style=invis] \n  } ordering=out\n  x [style=invis]\n  x -> { \"PL\" -> \"J\" -> \"NR\" -> \"AR\" [style=invis] } [style=invis] \"PL\" -> \"PL\"[minlen=0,fontsize=8,color=grey,xlabel=\" 0.432\"]\n\"J\" -> \"J\"[minlen=0,fontsize=8,color=grey,xlabel=\" 0.846\"]\n\"J\" -> \"NR\"[minlen=3,fontsize=8,color=grey,xlabel=\" 0.003\"]\n\"J\" -> \"AR\"[minlen=6,fontsize=8,color=grey,xlabel=\" 0.089\"]\n\"NR\" -> \"NR\"[minlen=0,fontsize=8,color=grey,xlabel=\" 0.795\"]\n\"NR\" -> \"AR\"[minlen=3,fontsize=8,color=grey,xlabel=\" 0.184\"]\n\"AR\" -> \"PL\"[minlen=-9,fontsize=8,color=grey,xlabel=\" 0.15\"]\n\"AR\" -> \"NR\"[minlen=-3,fontsize=8,color=grey,xlabel=\" 0.23\"]\n\"AR\" -> \"AR\"[minlen=0,fontsize=8,color=grey,xlabel=\" 0.751\"]\n labelloc=\"t\";\n  label=\"  \"\n}","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">isErgodic</span>(Lr1_No_erg, <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">return.eigvec =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<hr>
</section>
<section id="elementos-no-negativa" class="level3" data-number="10.7.3">
<h3 data-number="10.7.3" class="anchored" data-anchor-id="elementos-no-negativa"><span class="header-section-number">10.7.3</span> Elementos no negativa</h3>
<p>Una matriz poblacional debe ser no negativa, lo que significa que todas sus entradas son mayores o iguales a cero. ¿Por qué? Porque cada valor representa el número o la proporción de individuos que pasan de una etapa a otra. Tener valores negativos no tendría sentido biológico: no puede haber “menos” individuos que los existentes.</p>
<p>Además, si la matriz tuviera elementos negativos:</p>
<ul>
<li>No podríamos comparar correctamente las categorías de edad o estado.</li>
<li>Sería imposible calcular la tasa de crecimiento poblacional.</li>
</ul>
<p>En el caso de <em>L. rubripetala</em>, la matriz cumple esta condición, ya que todos sus valores son mayores o iguales a cero. En R, esto se puede verificar con la función <code>isPositive</code>, que devuelve:</p>
<ul>
<li>TRUE si la matriz es no negativa,</li>
<li>FALSE si contiene algún valor negativo</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># No negativa </span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>IsPositive <span class="ot">&lt;-</span> <span class="cf">function</span>(mat) {</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">all</span>(mat <span class="sc">&gt;=</span> <span class="dv">0</span>)) {</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="cn">TRUE</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="cn">FALSE</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="fu">IsPositive</span>(Lr1)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>A continuación se muestra un ejemplo de una matriz que no cumple la propiedad de no negatividad. En este caso, el elemento ubicado en la posición (4, 3) es negativo, lo que indica que la transición desde la categoría adulto reproductivo hacia adulto no reproductivo tiene un valor inválido.</p>
<p>Al evaluar esta matriz con la función <code>isPositive</code> en R, el resultado es FALSE. Esto significa que:</p>
<ul>
<li>La matriz no es válida para el análisis de dinámica poblacional.</li>
<li>No se puede esperar que la población alcance una estructura estable ni una tasa de crecimiento constante a largo plazo.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Capturar los datos de la matriz para L. rubripetala (Tremblay et al. 2015)</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>Lr1_No_pos<span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">0.4324</span>, <span class="dv">0</span>,      <span class="dv">0</span>,     <span class="fl">0.15</span>,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>               <span class="fl">0.3784</span>, <span class="fl">0.8459</span>, <span class="dv">0</span>,     <span class="dv">0</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>               <span class="dv">0</span>,      <span class="fl">0.0034</span>, <span class="fl">0.7954</span>,<span class="sc">-</span><span class="fl">0.2300</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>               <span class="dv">0</span>,      <span class="fl">0.0890</span>, <span class="fl">0.1841</span>,<span class="fl">0.7510</span>), <span class="at">byrow=</span><span class="cn">TRUE</span>,<span class="at">ncol=</span><span class="dv">4</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="fu">IsPositive</span>(Lr1_No_pos)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<hr>
</section>
<section id="irreducibilidad" class="level3" data-number="10.7.4">
<h3 data-number="10.7.4" class="anchored" data-anchor-id="irreducibilidad"><span class="header-section-number">10.7.4</span> Irreducibilidad</h3>
<p>Una matriz de transición poblacional debe ser irreducible, lo que significa que todas sus categorías están conectadas y existe al menos una ruta que permite llegar desde cualquier estado a los demás. Esta propiedad es esencial porque, si la matriz no es irreducible, la población no podrá alcanzar una estructura estable ni una tasa de crecimiento constante a largo plazo.</p>
<p>En el caso de <em>L. rubripetala</em>, la matriz es irreducible: todas las etapas del ciclo de vida están conectadas y existe una ruta entre ellas. Para comprobar esta propiedad en R, se utiliza la función <code>isIrreducible</code> del paquete popdemo, que devuelve:</p>
<ul>
<li>TRUE si la matriz es irreducible,</li>
<li>FALSE si no lo es.</li>
</ul>
<p>Es importante destacar que no todas las matrices reducibles son inválidas. En algunos casos, pueden aceptarse, por ejemplo, en especies con etapas que no influyen en el crecimiento poblacional, como las fases postreproductivas en mamíferos (humanos, ballenas, etc.).</p>
<p>En resumen, para <em>L. rubripetala</em>, la función <code>isIrreducible</code> devuelve TRUE, lo que confirma que todas las categorías están conectadas y que la población puede alcanzar una estructura estable y una tasa de crecimiento constante a largo plazo.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">isIrreducible</span>(Lr1)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>A continuación se muestra un ejemplo de matriz en la que el cuarto estadio no presenta valores de reproducción. Al evaluar esta matriz con la función <code>isIrreducible</code> en R, el resultado es FALSE.</p>
<p>¿Por qué ocurre esto? Porque no existe un vínculo entre la categoría plántula y la categoría adulto reproductivo, lo que significa que la presencia de plántulas en la población no contribuye a la reproducción.</p>
<p>Esta ausencia de conexión provoca dos problemas:</p>
<ul>
<li>Un ciclo de vida incompleto, como se observa en la imagen.</li>
<li>Una población que no podrá alcanzar una estructura estable ni una tasa de crecimiento constante a largo plazo.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>Lr1_Irr <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">0.4324</span>,  <span class="fl">0.</span>,       <span class="fl">0.0</span>,     <span class="dv">0</span>,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fl">0.3784</span>,  <span class="fl">0.8459</span>,   <span class="dv">0</span>,       <span class="dv">0</span>,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fl">0.</span>,      <span class="fl">0.0034</span>,   <span class="fl">0.7954</span>,  <span class="fl">0.2300</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                    <span class="dv">0</span>,       <span class="fl">0.0890</span>,   <span class="fl">0.1841</span>,  <span class="fl">0.7510</span>), <span class="at">byrow=</span><span class="cn">TRUE</span>,<span class="at">ncol=</span><span class="dv">4</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_life_cycle</span>(Lr1_Irr, <span class="at">stages =</span> estadios, <span class="at">fontsize =</span> <span class="dv">8</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="grViz html-widget html-fill-item" id="htmlwidget-d0d043e446d3efa46926" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-d0d043e446d3efa46926">{"x":{"diagram":"\ndigraph {\n  {\n    graph[overlap=false];\n    rank=same;\n    node [shape= egg , fontsize= 12 ]; \"PL\" -> \"J\" -> \"NR\" -> \"AR\" [style=invis] \n  } ordering=out\n  x [style=invis]\n  x -> { \"PL\" -> \"J\" -> \"NR\" -> \"AR\" [style=invis] } [style=invis] \"PL\" -> \"PL\"[minlen=0,fontsize=8,color=grey,xlabel=\" 0.432\"]\n\"PL\" -> \"J\"[minlen=3,fontsize=8,color=grey,xlabel=\" 0.378\"]\n\"J\" -> \"J\"[minlen=0,fontsize=8,color=grey,xlabel=\" 0.846\"]\n\"J\" -> \"NR\"[minlen=3,fontsize=8,color=grey,xlabel=\" 0.003\"]\n\"J\" -> \"AR\"[minlen=6,fontsize=8,color=grey,xlabel=\" 0.089\"]\n\"NR\" -> \"NR\"[minlen=0,fontsize=8,color=grey,xlabel=\" 0.795\"]\n\"NR\" -> \"AR\"[minlen=3,fontsize=8,color=grey,xlabel=\" 0.184\"]\n\"AR\" -> \"NR\"[minlen=-3,fontsize=8,color=grey,xlabel=\" 0.23\"]\n\"AR\" -> \"AR\"[minlen=0,fontsize=8,color=grey,xlabel=\" 0.751\"]\n labelloc=\"t\";\n  label=\"  \"\n}","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">isIrreducible</span>(Lr1_Irr)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<hr>
</section>
<section id="primitividad" class="level3" data-number="10.7.5">
<h3 data-number="10.7.5" class="anchored" data-anchor-id="primitividad"><span class="header-section-number">10.7.5</span> Primitividad</h3>
<p>Una matriz de transición poblacional debe ser primitiva, lo que significa que, al elevarla a potencias altas, se obtiene un único valor positivo dominante (la tasa de crecimiento poblacional). Esta propiedad es clave porque asegura que la población alcanzará una estructura estable y una tasa de crecimiento constante a largo plazo.</p>
<p>En el caso de <em>L. rubripetala</em>, la matriz es primitiva: al elevarla a potencias altas, aparece un único valor positivo. En R, esto se puede comprobar con la función <code>isPrimitive</code> del paquete popdemo, que devuelve:</p>
<ul>
<li>TRUE si la matriz es primitiva,</li>
<li>FALSE si no lo es.</li>
</ul>
<p>Una matriz no primitiva tendría una dinámica inestable a largo plazo, como ocurre en poblaciones con comportamiento cíclico, donde las proporciones entre categorías oscilan sin llegar a estabilizarse.</p>
<p>Es importante señalar que:</p>
<ul>
<li>Toda matriz irreducible es primitiva,</li>
<li>Pero no toda matriz primitiva es irreducible. Por ejemplo, una matriz puede ser primitiva sin ser irreducible si incluye un ciclo de vida completo, pero alguna etapa no influye en el crecimiento poblacional (como fases postreproductivas).</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">isPrimitive</span>(Lr1)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<hr>
</section>
</section>
<section id="índices-de-descripción-de-la-matriz-poblacional" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="índices-de-descripción-de-la-matriz-poblacional"><span class="header-section-number">10.8</span> Índices de descripción de la matriz poblacional</h2>
<p>En esta sección se revisan los índices poblacionales obtenidos a partir del análisis de matricial, los cuales se estiman una vez que ha verificado que cumplen con los supuestos. Estos índices permiten comprender el comportamiento de la población a largo plazo y anticipar cómo se espera que se comporte en el tiempo. Los índices que se abordan a continuación son: <strong>estructura estable</strong>, <strong>valor reproductivo</strong>, <strong>análisis de convergencia</strong> y <strong>análisis de amortiguamiento</strong>. Todos estos se calculan a partir de la matriz de transición poblacional y del vector de la estructura poblacional observada al inicio del estudio.</p>
<hr>
<section id="estructura-estable" class="level3" data-number="10.8.1">
<h3 data-number="10.8.1" class="anchored" data-anchor-id="estructura-estable"><span class="header-section-number">10.8.1</span> Estructura Estable</h3>
<p>La estructura poblacional estable (W, también conocida como eigenvector derecho) indica la proporción esperada de individuos en cada categoría de edad o estado cuando la población ha alcanzado el equilibrio a largo plazo. Por ejemplo, en L. rubripetala se espera que la estructura estable sea:</p>
<ul>
<li>Plántulas: 0.088</li>
<li>Juveniles: 0.206</li>
<li>Adultos no reproductivos: 0.369</li>
<li>Adultos reproductivos: 0.337</li>
</ul>
<p>Este índice supone que la tasa de crecimiento poblacional (<span class="math inline">\(\lambda\)</span>) se mantiene constante en el tiempo, lo cual solo ocurre bajo condiciones ambientales estables. Sin embargo, en la naturaleza esto es poco común. Además, la estructura estable asume que el periodo de muestreo y las condiciones abióticas y bióticas son típicas y no cambian.</p>
<p>En la revisión de Williams y colaboradores <span class="citation" data-cites="williams2011distance">(<a href="#ref-williams2011distance" role="doc-biblioref">Williams et&nbsp;al., 2011</a>)</span>, se reportó que más del 80% de las poblaciones analizadas no cumplían con la condición de estructura estable, especialmente en especies con matrices grandes (n × n) y tiempos generacionales prolongados. De manera similar, Tremblay (com. pers.) observó que la mayoría de las orquídeas estudiadas no estaban en estructura estable al inicio del muestreo poblacional.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Estructura estable de estados</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stable.stage</span>(Lr1)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        PL          J         NR         AR 
0.08789851 0.20619682 0.36907404 0.33683063 </code></pre>
</div>
</div>
<p>Uno puede visualizar la estructura poblacional usando el código siguiente.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>Wmax <span class="ot">&lt;-</span> <span class="fu">stable.stage</span>(Lr1)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>Wdf <span class="ot">=</span> <span class="fu">data.frame</span>(Wmax)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>Wdf<span class="sc">$</span>Categorias <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Plántulas"</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Juveniles"</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Adultos no reproductivos"</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Adultos reproductivos"</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>Wdf<span class="sc">$</span>Categorias <span class="ot">=</span> <span class="fu">factor</span>(</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  Wdf<span class="sc">$</span>Categorias,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Plántulas"</span>,</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Juveniles"</span>,</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Adultos no reproductivos"</span>,</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Adultos reproductivos"</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Wdf, <span class="fu">aes</span>(<span class="at">y =</span> Wmax, <span class="at">x =</span> Categorias)) <span class="sc">+</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="fu">aes</span>(<span class="at">fill =</span> <span class="st">"blue"</span>)) <span class="sc">+</span></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Estructura estable de estados esperada"</span>,</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Etapas"</span>,</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proporción"</span></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rlt_style_fill</span>()<span class="sc">+</span></span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))<span class="sc">+</span></span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"null"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="110-Propriedades_files/figure-html/Indice10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="valor-reproductivo" class="level3" data-number="10.8.2">
<h3 data-number="10.8.2" class="anchored" data-anchor-id="valor-reproductivo"><span class="header-section-number">10.8.2</span> Valor reproductivo</h3>
<div class="img-float">
<div class="quarto-figure quarto-figure-center" style="float: left; margin: 10px;width: 40% ; ">
<figure class="figure">
<p><img src="Species/Spathoglottis plicata Tremblay.jpeg" class="img-fluid figure-img"></p>
<figcaption><em>Spathoglottis plicata</em>. Foto: Tremblay</figcaption>
</figure>
</div>
</div>
<p>El valor reproductivo (v, también llamado eigenvector izquierdo) indica la contribución esperada de cada categoría de edad o estado a la reproducción de la población.</p>
<p>En el caso de L. rubripetala, los valores reproductivos esperados son:</p>
<ul>
<li>Plántulas: 1.00</li>
<li>Juveniles: 1.52</li>
<li>Adultos no reproductivos: 2.32</li>
<li>Adultos reproductivos: 2.66</li>
</ul>
<p>Este índice es muy útil porque muestra qué etapas son más importantes para el crecimiento poblacional a largo plazo. La primera categoría siempre tiene un valor de 1.00, ya que representa el inicio del ciclo de vida y sirve como referencia para calcular los demás valores.</p>
<p>Además, el valor reproductivo ayuda a definir estrategias de manejo. Por ejemplo:</p>
<ul>
<li><p>En <em>Spathoglottis plicata</em>, una orquídea terrestre invasora, las acciones de control deberían enfocarse en las categorías con mayor valor reproductivo, porque son las que más contribuyen al crecimiento poblacional.</p></li>
<li><p>Por el contrario, si se busca remover individuos con el menor impacto posible, conviene actuar sobre las etapas con valores reproductivos bajos.</p></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valor reproductivo</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">reproductive.value</span>(Lr1)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      PL        J       NR       AR 
1.000000 1.519043 2.316113 2.664676 </code></pre>
</div>
</div>
<hr>
</section>
<section id="análisis-de-convergencia-y-amortigamiento-damping-ratio" class="level3" data-number="10.8.3">
<h3 data-number="10.8.3" class="anchored" data-anchor-id="análisis-de-convergencia-y-amortigamiento-damping-ratio"><span class="header-section-number">10.8.3</span> Análisis de Convergencia y Amortigamiento (Damping ratio)</h3>
<p>El análisis de convergencia mide el tiempo esperado para que una población alcance su estructura estable y un crecimiento asintótico después de un disturbio. Es decir, indica qué tan rápido la población regresa a su estructura estable tras una perturbación <span class="citation" data-cites="stott2011framework">(<a href="#ref-stott2011framework" role="doc-biblioref">Stott, Townley &amp; Hodgson, 2011</a>)</span>. Este comportamiento se cuantifica mediante el índice de amortiguamiento (damping ratio), que evalúa la influencia del valor propio subdominante, <span class="math inline">\(\lambda_2\)</span>, durante el periodo de convergencia.</p>
<p>El índice se expresa a través del cociente entre el valor propio dominante, <span class="math inline">\(\lambda_1\)</span>, y el valor absoluto del subdominante <span class="math display">\[\mathbf{\rho=\frac{\lambda_1}{\left|\lambda_2\right|}}\]</span>; dónde <span class="math inline">\(\rho\)</span> representa el índice de amortiguamiento, <span class="math inline">\(\lambda_1\)</span> corresponde al valor propio dominante de la matriz de transición poblacional y <span class="math inline">\(\lambda_2\)</span> al módulo del segundo valor propio más grande. Este índice no tiene unidades y es independiente de la estructura inicial de la población.</p>
<p>En el caso de <em>L. rubripetala</em>, al calcular los valores propios de la matriz con la función <strong>eigen</strong>, se obtiene un valor dominante de <span class="math inline">\(\lambda_1= 1.00721\)</span> y un valor subdominante de <span class="math inline">\(\lambda_2= 0.8319\)</span>. De esta manera el índice de amortiguamiento es:</p>
<p><span class="math display">\[
\rho = \frac{\lambda_1}{|\lambda_2|} = \frac{1.00721}{|0.83192|} \approx 1.21
\]</span></p>
<p>El valor obtenido indica que la población converge hacia su estructura estable tras un disturbio; aunque, lentamente.</p>
<p>Es importante señalar que la interpretación de este índice depende de la escala temporal con que se construyó la matriz. Si bien la mayoría de los estudios poblacionales utilizan datos anuales <span class="citation" data-cites="crone2011plant">(<a href="#ref-crone2011plant" role="doc-biblioref">Crone et&nbsp;al., 2011</a>)</span>, también existen estudios con periodos de muestreo mensuales, bimensuales, estacionales o bianuales, los cuales se establecen de acuerdo con el ciclo de vida de la especie estudiada.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eigen</span>(Lr1)<span class="sc">$</span>values <span class="co"># la lista de valores propios de la matriz Lr1</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.0072061+0.00000000i 0.8319189+0.00000000i 0.4927875+0.06468183i
[4] 0.4927875-0.06468183i</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>DR <span class="ot">=</span> <span class="fu">eigen</span>(Lr1)<span class="sc">$</span>values[<span class="dv">1</span>] <span class="sc">/</span> <span class="fu">abs</span>(<span class="fu">eigen</span>(Lr1)<span class="sc">$</span>values[<span class="dv">2</span>])</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>DR</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.210702+0i</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dr</span>(Lr1) <span class="co"># usando la función "dr" para "damping ratio" en el paquete "popdemo"</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.210702</code></pre>
</div>
</div>
</section>
<section id="graficación-del-índice-de-amortiguamiento" class="level3" data-number="10.8.4">
<h3 data-number="10.8.4" class="anchored" data-anchor-id="graficación-del-índice-de-amortiguamiento"><span class="header-section-number">10.8.4</span> Graficación del Índice de amortiguamiento</h3>
<p>El comportamiento del índice de amortiguamiento se puede visualizar mediante una gráfica de líneas, que muestra cómo responde un sistema ante un cambio súbito (un “paso de entrada”) y cómo varía esa respuesta en el tiempo según diferentes niveles de amortiguamiento.</p>
<p>Para facilitar la comprensión, en el siguiente bloque se incluye el código que genera una gráfica ilustrando el comportamiento de una población perturbada:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Definir los parametros ---</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Población inicial en el tiempo t=0. Ese el punto de equilibrio inicial.</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>poblacion_inicial <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Factores de amortiguamiento para graficar.</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 0,3 = Subamortiguado (oscila)</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 1,0 = Críticamente amortiguado (retorno más rápido sin oscilación)</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 2,0 = Sobreamortiguado (retorno lento sin oscilación)</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>amortigamento <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.3</span>, <span class="fl">1.0</span>, <span class="fl">2.0</span>, <span class="fl">3.0</span>)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Frecuencia de la oscilación (omega_n).</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>frecuencia <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Tiempo total para la simulación</span></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>tiempo_total <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso de tiempo para la simulación (más pequeño para una curva más suave)</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>etapa_tiempo <span class="ot">&lt;-</span> <span class="fl">0.1</span></span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Generate the Damped Oscillation Data for Multiple Ratios ---</span></span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Create an empty data frame to store all the data</span></span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a>todo_data_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Recorra cada relación de amortiguamiento para generar los datos</span></span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (zeta <span class="cf">in</span> amortigamento) {</span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create a sequence of time points</span></span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a>  time_points <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, tiempo_total, <span class="at">by =</span> etapa_tiempo)</span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate the population at each time point based on the damping ratio.</span></span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a>  <span class="co"># The mathematical form of the step response changes depending on the damping ratio.</span></span>
<span id="cb33-33"><a href="#cb33-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-34"><a href="#cb33-34" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (zeta <span class="sc">&lt;</span> <span class="dv">1</span>) {</span>
<span id="cb33-35"><a href="#cb33-35" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Underdamped case: damped sine wave</span></span>
<span id="cb33-36"><a href="#cb33-36" aria-hidden="true" tabindex="-1"></a>    omega_d <span class="ot">&lt;-</span> frecuencia <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">-</span> zeta<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb33-37"><a href="#cb33-37" aria-hidden="true" tabindex="-1"></a>    population_data <span class="ot">&lt;-</span> poblacion_inicial <span class="sc">*</span></span>
<span id="cb33-38"><a href="#cb33-38" aria-hidden="true" tabindex="-1"></a>      (<span class="dv">1</span> <span class="sc">-</span></span>
<span id="cb33-39"><a href="#cb33-39" aria-hidden="true" tabindex="-1"></a>        <span class="fu">exp</span>(<span class="sc">-</span>zeta <span class="sc">*</span> frecuencia <span class="sc">*</span> time_points) <span class="sc">*</span></span>
<span id="cb33-40"><a href="#cb33-40" aria-hidden="true" tabindex="-1"></a>          (<span class="fu">cos</span>(omega_d <span class="sc">*</span> time_points) <span class="sc">+</span></span>
<span id="cb33-41"><a href="#cb33-41" aria-hidden="true" tabindex="-1"></a>            (zeta <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">-</span> zeta<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">*</span> <span class="fu">sin</span>(omega_d <span class="sc">*</span> time_points)))</span>
<span id="cb33-42"><a href="#cb33-42" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (zeta <span class="sc">==</span> <span class="dv">1</span>) {</span>
<span id="cb33-43"><a href="#cb33-43" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Critically Damped case</span></span>
<span id="cb33-44"><a href="#cb33-44" aria-hidden="true" tabindex="-1"></a>    population_data <span class="ot">&lt;-</span> poblacion_inicial <span class="sc">*</span></span>
<span id="cb33-45"><a href="#cb33-45" aria-hidden="true" tabindex="-1"></a>      (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(<span class="sc">-</span>frecuencia <span class="sc">*</span> time_points) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">+</span> frecuencia <span class="sc">*</span> time_points))</span>
<span id="cb33-46"><a href="#cb33-46" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb33-47"><a href="#cb33-47" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Overdamped case</span></span>
<span id="cb33-48"><a href="#cb33-48" aria-hidden="true" tabindex="-1"></a>    s1 <span class="ot">&lt;-</span> <span class="sc">-</span>zeta <span class="sc">*</span> frecuencia <span class="sc">+</span> frecuencia <span class="sc">*</span> <span class="fu">sqrt</span>(zeta<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb33-49"><a href="#cb33-49" aria-hidden="true" tabindex="-1"></a>    s2 <span class="ot">&lt;-</span> <span class="sc">-</span>zeta <span class="sc">*</span> frecuencia <span class="sc">-</span> frecuencia <span class="sc">*</span> <span class="fu">sqrt</span>(zeta<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb33-50"><a href="#cb33-50" aria-hidden="true" tabindex="-1"></a>    population_data <span class="ot">&lt;-</span> poblacion_inicial <span class="sc">*</span></span>
<span id="cb33-51"><a href="#cb33-51" aria-hidden="true" tabindex="-1"></a>      (<span class="dv">1</span> <span class="sc">-</span></span>
<span id="cb33-52"><a href="#cb33-52" aria-hidden="true" tabindex="-1"></a>        (s2 <span class="sc">*</span> <span class="fu">exp</span>(s1 <span class="sc">*</span> time_points) <span class="sc">-</span> s1 <span class="sc">*</span> <span class="fu">exp</span>(s2 <span class="sc">*</span> time_points)) <span class="sc">/</span> (s2 <span class="sc">-</span> s1))</span>
<span id="cb33-53"><a href="#cb33-53" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb33-54"><a href="#cb33-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-55"><a href="#cb33-55" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add the data for the current damping ratio to a temporary data frame</span></span>
<span id="cb33-56"><a href="#cb33-56" aria-hidden="true" tabindex="-1"></a>  temp_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb33-57"><a href="#cb33-57" aria-hidden="true" tabindex="-1"></a>    <span class="at">Time =</span> time_points,</span>
<span id="cb33-58"><a href="#cb33-58" aria-hidden="true" tabindex="-1"></a>    <span class="at">Population =</span> population_data,</span>
<span id="cb33-59"><a href="#cb33-59" aria-hidden="true" tabindex="-1"></a>    <span class="at">DampingRatio =</span> <span class="fu">factor</span>(zeta) <span class="co"># Store damping ratio as a factor for coloring</span></span>
<span id="cb33-60"><a href="#cb33-60" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb33-61"><a href="#cb33-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-62"><a href="#cb33-62" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Bind the temporary data frame to the main data frame</span></span>
<span id="cb33-63"><a href="#cb33-63" aria-hidden="true" tabindex="-1"></a>  todo_data_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(todo_data_df, temp_df)</span>
<span id="cb33-64"><a href="#cb33-64" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb33-65"><a href="#cb33-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-66"><a href="#cb33-66" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Create the Plot using ggplot2 ---</span></span>
<span id="cb33-67"><a href="#cb33-67" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(todo_data_df, <span class="fu">aes</span>(<span class="at">x =</span> Time, <span class="at">y =</span> Population, <span class="at">color =</span> DampingRatio)) <span class="sc">+</span></span>
<span id="cb33-68"><a href="#cb33-68" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add the lines for each damping ratio</span></span>
<span id="cb33-69"><a href="#cb33-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb33-70"><a href="#cb33-70" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Set the title and labels</span></span>
<span id="cb33-71"><a href="#cb33-71" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb33-72"><a href="#cb33-72" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"El efecto de amortigamento </span><span class="sc">\n</span><span class="st"> sobre el tamaño de población"</span>,</span>
<span id="cb33-73"><a href="#cb33-73" aria-hidden="true" tabindex="-1"></a>  <span class="at">subtitle =</span> <span class="st">"La población se estabiliza a un equilibrio de 1000"</span>,</span>
<span id="cb33-74"><a href="#cb33-74" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="st">"Tiempo"</span>,</span>
<span id="cb33-75"><a href="#cb33-75" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="st">"Tamaño poblacional"</span>,</span>
<span id="cb33-76"><a href="#cb33-76" aria-hidden="true" tabindex="-1"></a>  <span class="at">color =</span> <span class="fu">expression</span>(<span class="st">"Amortigamento ("</span> <span class="sc">*</span> zeta <span class="sc">*</span> <span class="st">")"</span>)</span>
<span id="cb33-77"><a href="#cb33-77" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb33-78"><a href="#cb33-78" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Customize the plot theme for better aesthetics</span></span>
<span id="cb33-79"><a href="#cb33-79" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rlt_style_colour</span>() <span class="sc">+</span></span>
<span id="cb33-80"><a href="#cb33-80" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb33-81"><a href="#cb33-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb33-82"><a href="#cb33-82" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb33-83"><a href="#cb33-83" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb33-84"><a href="#cb33-84" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb33-85"><a href="#cb33-85" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="110-Propriedades_files/figure-html/Indice13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="intepretación-del-gráfico-de-amortiguamiento" class="level3" data-number="10.8.5">
<h3 data-number="10.8.5" class="anchored" data-anchor-id="intepretación-del-gráfico-de-amortiguamiento"><span class="header-section-number">10.8.5</span> Intepretación del gráfico de amortiguamiento</h3>
<p>La figura resultante ilustra el efecto de diferentes coeficientes de amortiguamiento en la respuesta de una población a un cambio súbito. El gráfico muestra cuatro comportamientos distintos para la población perturbada y su retorno a un estado de equilibrio, correspondiente a un tamaño poblacional de 1000 individuos.</p>
<p>La respuesta de la población ante cuatro índices de amortiguamiento es la siguiente:</p>
<p>• Subamortiguado (ζ=0.3): Esta es la respuesta oscilante. El sistema sobrepasa el punto de equilibrio y luego oscila, con el tiempo la amplitud de las oscilaciones disminuyen gradualmente hasta estabilizarse en el equilibrio.</p>
<p>• Amortiguado críticamente (ζ=1.0): Esta es la respuesta más rápida, la cual alcanza el equilibrio sin oscilaciones ni sobreamortiguaciones. Se considera la respuesta ideal para sistemas que requieren un retorno rápido y estable al valor objetivo.</p>
<p>• Sobreamortiguado (ζ=2.0): Esta respuesta es lenta y se aproxima al punto de equilibrio sin oscilaciones. En comparación con el caso críticamente amortiguado, tarda mucho más en estabilizarse, ya que la fuerza de amortiguamiento es muy grande.</p>
<p>• Sobreamortiguado (ζ=3.0): Similar al caso anterior, pero con un amortiguamiento aún mayor. La respuesta es muy lenta y se acerca al equilibrio de manera gradual sin oscilaciones.</p>
<section id="tiempo-de-convergencia" class="level4" data-number="10.8.5.1">
<h4 data-number="10.8.5.1" class="anchored" data-anchor-id="tiempo-de-convergencia"><span class="header-section-number">10.8.5.1</span> Tiempo de Convergencia</h4>
<p>El tiempo de convergencia es el periodo estimado que tarda la población en alcanzar su estructura estable. Este índice es relevante porque facilita entender el comportamiento poblacional a largo plazo. En <strong>R</strong> este cálculo puede realizarse con dos funciones del paquete <strong>popdemo</strong>: <strong>dr</strong> y <strong>convt</strong>. La función <strong>dr</strong> calcula el amortiguamiento y a partir de éste puede estimarse el tiempo de la convergencia de la siguiente manera:</p>
<p><span class="math display">\[
t = \frac{\log(dr)}{\log(x)}
\]</span></p>
<p>dónde</p>
<ul>
<li><span class="math inline">\(dr\)</span> es el índice de amortiguamiento (damping ratio)</li>
<li><span class="math inline">\(x\)</span> es un factor de comparación</li>
<li><span class="math inline">\(t\)</span> representa el tiempo en la misma unidad en que se construyó la matriz (días, meses, años, etc.).</li>
</ul>
<p>El análisis de amortiguamiento estima la rapidez con la que una población converge a su estructura estable después de un disturbio <span class="citation" data-cites="jiang2020life">(<a href="#ref-jiang2020life" role="doc-biblioref">Jiang et&nbsp;al., 2020</a>)</span>. El índice de amortiguamiento (<span class="math inline">\(d &gt; 0\)</span>) sugiere que mientras mayor sea su valor, más rápida será la convergencia. El tiempo de amortiguamiento se calcula como: <span class="math inline">\(\tau=1/d\)</span>, dónde <span class="math inline">\(\tau\)</span> expresa la duración del proceso de convergencia en unidades de tiempo consistentes con la matriz poblacional. Cabe señalar que, se ha demostrado que existe una relación entre el índice de amortiguamiento y el tiempo generacional de una especie <span class="citation" data-cites="jiang2020life">(<a href="#ref-jiang2020life" role="doc-biblioref">Jiang et&nbsp;al., 2020</a>)</span>.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dr</span>(Lr1, <span class="at">return.time =</span> <span class="cn">TRUE</span>, <span class="at">x =</span> <span class="dv">10</span>) <span class="co"># cuanto tiempo toma aumentar la población de veces </span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$dr
[1] 1.210702

$t
[1] 12.04278</code></pre>
</div>
</div>
<p>A partir de la la función <span class="math inline">\(contv\)</span> del paquete <strong>popdemo</strong> se puede estimar el tiempo esperado en que una población alcanza su estructura estable, considerando la estructura poblacional observada al inicio del estudio. Esta función simula el modelo y determina manualmente cuándo la población converge, dado un nivel de exactitud especifico (<em>accuracy</em>). Entre más estricta sea la exactitud, mayor será el tiempo de convergencia. Para utilizar esta función es necesario indicar la estructura inicial, es decir, el número de individuos en cada estadio. En el caso de <em>L. rubripetala</em> se espera que el tiempo de convergencia sea de 18 ciclos (meses) para alcanzar su estructura estable.</p>
<p>Por ejemplo, si se comienza con una población inicial de 8, 20, 27 y 34 individuos en las categorías de plántulas, juveniles, adultos no reproductivos y adultos reproductivos, respectivamente, la población alcanzaría en 6 meses, aproximadamente, la estructura estable. En contraste, si la población inicial estuviera sesgada (compuesta únicamente por plántulas, por ejemplo), el tiempo de convergencia sería mucho mayor. Este enfoque resulta muy útil al definir estrategias de conservación; por ejemplo, al establecer una nueva población con una distribución inicial determinada.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>n0 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">20</span>, <span class="dv">27</span>, <span class="dv">34</span>) <span class="co"># la estructura de la población inicial</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">convt</span>(Lr1, <span class="at">accuracy =</span> <span class="fl">1e-4</span>, <span class="at">vector =</span> n0, <span class="at">iterations =</span> <span class="dv">10000</span>) <span class="co"># la estructura poblacional inicial</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18</code></pre>
</div>
</div>
<p>Dado que el tiempo de convergencia es un índice que representa el periodo esperado para que una población alcance su estructura estable, se puede calcular variando la cantidad de individuos en las diferentes edades o estados al llevar a cabo una simulación.</p>
<p>Por ejemplo, se estima que <em>L. rubripetala</em> alcanzaría la estructura estable en 25 meses, si la población inicia con una población sesgada a plántulas (n = 1000) y, por lo tanto, sin la presencia de individuos de los estados posteriores.</p>
</section>
</section>
<section id="graficación-del-tiempo-de-convergencia-al-estado-estable-de-cada-etapa-de-vida" class="level3" data-number="10.8.6">
<h3 data-number="10.8.6" class="anchored" data-anchor-id="graficación-del-tiempo-de-convergencia-al-estado-estable-de-cada-etapa-de-vida"><span class="header-section-number">10.8.6</span> Graficación del tiempo de convergencia al estado estable de cada etapa de vida</h3>
<p>La población comienza en cada etapa con 100 individuos y se simula durante 22 pasos de tiempo. El gráfico resultante muestra cómo la población converge a su estructura estable a lo largo del tiempo, con cada etapa representada por una línea de color diferente. La línea horizontal indica el valor de la proporción de la etapa estable y la linea vertical representa a que tiempo se espera que la etapa llegua a su nivel de estructura estable.</p>
<p>Nota que si las condiciones se quedan igual en el tiempo se espera que la población converja a una estructura estable, es decir, que la proporción de individuos en cada etapa se mantenga constante a lo largo del tiempo. En este caso, la proporción de individuos en cada etapa converge a 0.088, 0.206, 0.369 y 0.337 para las categorías de plántulas, juveniles, adultos no reproductivos y adultos reproductivos, respectivamente 3, 17, 15 y 9 periodos (el tiempo de re-muestreo correspondiente a la construcción de la matrix).</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Este script utiliza un enfoque de matriz para modelar las dinámicas de una</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># población de 4 etapas (por ejemplo, clases de edad o estadios de vida).</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Demuestra cómo una distribución de población converge a un estado estable.</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Instalar y cargar el paquete ggplot2 para el trazado</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("ggplot2")</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Definir Parámetros de Simulación ---</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Población inicial en el tiempo t=0 para cada etapa.</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Una distribución inicial uniforme es un buen punto de partida para observar la convergencia.</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>initial_population <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">100</span>, <span class="dv">100</span>, <span class="dv">100</span>)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Número total de pasos de tiempo para la simulación</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>total_time_steps <span class="ot">&lt;-</span> <span class="dv">22</span></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Definir la Matriz de Transición de la Población (Leslie Matrix) ---</span></span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Se utiliza la matriz proporcionada por el usuario.</span></span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>transition_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">0.4324</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="fl">0.15</span>,</span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>                              <span class="fl">0.3784</span>, <span class="fl">0.8459</span>, <span class="dv">0</span>, <span class="dv">0</span>,</span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a>                              <span class="dv">0</span>, <span class="fl">0.0034</span>, <span class="fl">0.7954</span>, <span class="fl">0.2300</span>,</span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a>                              <span class="dv">0</span>, <span class="fl">0.0890</span>, <span class="fl">0.1841</span>, <span class="fl">0.7510</span>),</span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a>                    <span class="at">nrow =</span> <span class="dv">4</span>,</span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a>                    <span class="at">byrow =</span> <span class="cn">TRUE</span></span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-26"><a href="#cb38-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-27"><a href="#cb38-27" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Simular la Dinámica de la Población y Calcular Proporciones ---</span></span>
<span id="cb38-28"><a href="#cb38-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Nombres de las etapas en el orden especificado</span></span>
<span id="cb38-29"><a href="#cb38-29" aria-hidden="true" tabindex="-1"></a>stage_names <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb38-30"><a href="#cb38-30" aria-hidden="true" tabindex="-1"></a>  <span class="st">"juvenil"</span>,</span>
<span id="cb38-31"><a href="#cb38-31" aria-hidden="true" tabindex="-1"></a>  <span class="st">"plántula"</span>,</span>
<span id="cb38-32"><a href="#cb38-32" aria-hidden="true" tabindex="-1"></a>  <span class="st">"adulto no reproductivo"</span>,</span>
<span id="cb38-33"><a href="#cb38-33" aria-hidden="true" tabindex="-1"></a>  <span class="st">"adulto reproductivo"</span></span>
<span id="cb38-34"><a href="#cb38-34" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-35"><a href="#cb38-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-36"><a href="#cb38-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un data frame para almacenar los resultados de la simulación</span></span>
<span id="cb38-37"><a href="#cb38-37" aria-hidden="true" tabindex="-1"></a>all_data_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb38-38"><a href="#cb38-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">Time =</span> <span class="fu">integer</span>(),</span>
<span id="cb38-39"><a href="#cb38-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">Proportion =</span> <span class="fu">numeric</span>(),</span>
<span id="cb38-40"><a href="#cb38-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">Stage =</span> <span class="fu">character</span>()</span>
<span id="cb38-41"><a href="#cb38-41" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-42"><a href="#cb38-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-43"><a href="#cb38-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Vector de población actual (distribución inicial)</span></span>
<span id="cb38-44"><a href="#cb38-44" aria-hidden="true" tabindex="-1"></a>n_current <span class="ot">&lt;-</span> initial_population</span>
<span id="cb38-45"><a href="#cb38-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-46"><a href="#cb38-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Bucle para simular cada paso de tiempo</span></span>
<span id="cb38-47"><a href="#cb38-47" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (t <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>total_time_steps) {</span>
<span id="cb38-48"><a href="#cb38-48" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calcular la proporción de la población en cada etapa</span></span>
<span id="cb38-49"><a href="#cb38-49" aria-hidden="true" tabindex="-1"></a>  current_proportions <span class="ot">&lt;-</span> n_current <span class="sc">/</span> <span class="fu">sum</span>(n_current)</span>
<span id="cb38-50"><a href="#cb38-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-51"><a href="#cb38-51" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Crear un data frame temporal para este paso de tiempo</span></span>
<span id="cb38-52"><a href="#cb38-52" aria-hidden="true" tabindex="-1"></a>  temp_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb38-53"><a href="#cb38-53" aria-hidden="true" tabindex="-1"></a>    <span class="at">Time =</span> <span class="fu">rep</span>(t, <span class="dv">4</span>),</span>
<span id="cb38-54"><a href="#cb38-54" aria-hidden="true" tabindex="-1"></a>    <span class="at">Proportion =</span> current_proportions,</span>
<span id="cb38-55"><a href="#cb38-55" aria-hidden="true" tabindex="-1"></a>    <span class="at">Stage =</span> <span class="fu">factor</span>(stage_names, <span class="at">levels =</span> stage_names) <span class="co"># Se usa factor para ordenar las etapas</span></span>
<span id="cb38-56"><a href="#cb38-56" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb38-57"><a href="#cb38-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-58"><a href="#cb38-58" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Añadir los datos al data frame principal</span></span>
<span id="cb38-59"><a href="#cb38-59" aria-hidden="true" tabindex="-1"></a>  all_data_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(all_data_df, temp_df)</span>
<span id="cb38-60"><a href="#cb38-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-61"><a href="#cb38-61" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Proyectar la población al siguiente paso de tiempo</span></span>
<span id="cb38-62"><a href="#cb38-62" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Multiplicación de la matriz de transición por el vector de población</span></span>
<span id="cb38-63"><a href="#cb38-63" aria-hidden="true" tabindex="-1"></a>  n_next <span class="ot">&lt;-</span> transition_matrix <span class="sc">%*%</span> n_current</span>
<span id="cb38-64"><a href="#cb38-64" aria-hidden="true" tabindex="-1"></a>  n_current <span class="ot">&lt;-</span> n_next</span>
<span id="cb38-65"><a href="#cb38-65" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb38-66"><a href="#cb38-66" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Calcular la Distribución de Etapa Estable (SSD) ---</span></span>
<span id="cb38-67"><a href="#cb38-67" aria-hidden="true" tabindex="-1"></a><span class="co"># Se calcula el vector propio derecho (eigenvector) del valor propio dominante.</span></span>
<span id="cb38-68"><a href="#cb38-68" aria-hidden="true" tabindex="-1"></a><span class="co"># Este vector representa la proporción de individuos en cada etapa en el estado estable.</span></span>
<span id="cb38-69"><a href="#cb38-69" aria-hidden="true" tabindex="-1"></a>eigen_results <span class="ot">&lt;-</span> <span class="fu">eigen</span>(transition_matrix)</span>
<span id="cb38-70"><a href="#cb38-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-71"><a href="#cb38-71" aria-hidden="true" tabindex="-1"></a><span class="co"># Encontrar el valor propio dominante (más grande)</span></span>
<span id="cb38-72"><a href="#cb38-72" aria-hidden="true" tabindex="-1"></a>dominant_eigenvalue <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">Re</span>(eigen_results<span class="sc">$</span>values))</span>
<span id="cb38-73"><a href="#cb38-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-74"><a href="#cb38-74" aria-hidden="true" tabindex="-1"></a><span class="co"># Encontrar el vector propio derecho correspondiente (eigenvector)</span></span>
<span id="cb38-75"><a href="#cb38-75" aria-hidden="true" tabindex="-1"></a>stable_stage_distribution_raw <span class="ot">&lt;-</span> <span class="fu">Re</span>(eigen_results<span class="sc">$</span>vectors[, <span class="fu">which.max</span>(<span class="fu">Re</span>(</span>
<span id="cb38-76"><a href="#cb38-76" aria-hidden="true" tabindex="-1"></a>  eigen_results<span class="sc">$</span>values</span>
<span id="cb38-77"><a href="#cb38-77" aria-hidden="true" tabindex="-1"></a>))])</span>
<span id="cb38-78"><a href="#cb38-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-79"><a href="#cb38-79" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalizar el vector propio para que sume 1</span></span>
<span id="cb38-80"><a href="#cb38-80" aria-hidden="true" tabindex="-1"></a>stable_stage_distribution <span class="ot">&lt;-</span> stable_stage_distribution_raw <span class="sc">/</span></span>
<span id="cb38-81"><a href="#cb38-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(stable_stage_distribution_raw)</span>
<span id="cb38-82"><a href="#cb38-82" aria-hidden="true" tabindex="-1"></a>stable_stage_distribution_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb38-83"><a href="#cb38-83" aria-hidden="true" tabindex="-1"></a>  <span class="at">Stage =</span> <span class="fu">factor</span>(stage_names, <span class="at">levels =</span> stage_names),</span>
<span id="cb38-84"><a href="#cb38-84" aria-hidden="true" tabindex="-1"></a>  <span class="at">Proportion =</span> stable_stage_distribution</span>
<span id="cb38-85"><a href="#cb38-85" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-86"><a href="#cb38-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-87"><a href="#cb38-87" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Calcular el Tiempo de Convergencia para cada Etapa ---</span></span>
<span id="cb38-88"><a href="#cb38-88" aria-hidden="true" tabindex="-1"></a><span class="co"># Definir una tolerancia para la convergencia (por ejemplo, 1% de la proporción de SSD)</span></span>
<span id="cb38-89"><a href="#cb38-89" aria-hidden="true" tabindex="-1"></a>tolerance <span class="ot">&lt;-</span> <span class="fl">0.01</span></span>
<span id="cb38-90"><a href="#cb38-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-91"><a href="#cb38-91" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un data frame para almacenar los tiempos de convergencia</span></span>
<span id="cb38-92"><a href="#cb38-92" aria-hidden="true" tabindex="-1"></a>convergence_times_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb38-93"><a href="#cb38-93" aria-hidden="true" tabindex="-1"></a>  <span class="at">Stage =</span> <span class="fu">character</span>(),</span>
<span id="cb38-94"><a href="#cb38-94" aria-hidden="true" tabindex="-1"></a>  <span class="at">Time =</span> <span class="fu">numeric</span>()</span>
<span id="cb38-95"><a href="#cb38-95" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-96"><a href="#cb38-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-97"><a href="#cb38-97" aria-hidden="true" tabindex="-1"></a><span class="co"># Bucle a través de cada etapa para encontrar el primer paso de tiempo donde</span></span>
<span id="cb38-98"><a href="#cb38-98" aria-hidden="true" tabindex="-1"></a><span class="co"># la proporción está dentro de la tolerancia de la SSD</span></span>
<span id="cb38-99"><a href="#cb38-99" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(stage_names)) {</span>
<span id="cb38-100"><a href="#cb38-100" aria-hidden="true" tabindex="-1"></a>  stage_name <span class="ot">&lt;-</span> stage_names[i]</span>
<span id="cb38-101"><a href="#cb38-101" aria-hidden="true" tabindex="-1"></a>  ssd_proportion <span class="ot">&lt;-</span> stable_stage_distribution_df[</span>
<span id="cb38-102"><a href="#cb38-102" aria-hidden="true" tabindex="-1"></a>    stable_stage_distribution_df<span class="sc">$</span>Stage <span class="sc">==</span> stage_name,</span>
<span id="cb38-103"><a href="#cb38-103" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Proportion"</span></span>
<span id="cb38-104"><a href="#cb38-104" aria-hidden="true" tabindex="-1"></a>  ]</span>
<span id="cb38-105"><a href="#cb38-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-106"><a href="#cb38-106" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Filtrar los datos para la etapa actual</span></span>
<span id="cb38-107"><a href="#cb38-107" aria-hidden="true" tabindex="-1"></a>  stage_data <span class="ot">&lt;-</span> all_data_df[all_data_df<span class="sc">$</span>Stage <span class="sc">==</span> stage_name, ]</span>
<span id="cb38-108"><a href="#cb38-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-109"><a href="#cb38-109" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Encontrar la primera fila donde la proporción está dentro de la banda de tolerancia</span></span>
<span id="cb38-110"><a href="#cb38-110" aria-hidden="true" tabindex="-1"></a>  convergence_time <span class="ot">&lt;-</span> stage_data<span class="sc">$</span>Time[<span class="fu">which</span>(</span>
<span id="cb38-111"><a href="#cb38-111" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abs</span>(stage_data<span class="sc">$</span>Proportion <span class="sc">-</span> ssd_proportion) <span class="sc">&lt;=</span> tolerance</span>
<span id="cb38-112"><a href="#cb38-112" aria-hidden="true" tabindex="-1"></a>  )[<span class="dv">1</span>]]</span>
<span id="cb38-113"><a href="#cb38-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-114"><a href="#cb38-114" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.na</span>(convergence_time)) {</span>
<span id="cb38-115"><a href="#cb38-115" aria-hidden="true" tabindex="-1"></a>    convergence_times_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb38-116"><a href="#cb38-116" aria-hidden="true" tabindex="-1"></a>      convergence_times_df,</span>
<span id="cb38-117"><a href="#cb38-117" aria-hidden="true" tabindex="-1"></a>      <span class="fu">data.frame</span>(</span>
<span id="cb38-118"><a href="#cb38-118" aria-hidden="true" tabindex="-1"></a>        <span class="at">Stage =</span> stage_name,</span>
<span id="cb38-119"><a href="#cb38-119" aria-hidden="true" tabindex="-1"></a>        <span class="at">Time =</span> convergence_time</span>
<span id="cb38-120"><a href="#cb38-120" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb38-121"><a href="#cb38-121" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb38-122"><a href="#cb38-122" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb38-123"><a href="#cb38-123" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb38-124"><a href="#cb38-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-125"><a href="#cb38-125" aria-hidden="true" tabindex="-1"></a><span class="co"># La función `factor` es necesaria para garantizar que los nombres de las etapas</span></span>
<span id="cb38-126"><a href="#cb38-126" aria-hidden="true" tabindex="-1"></a><span class="co"># en `convergence_times_df` se muestren en el orden correcto.</span></span>
<span id="cb38-127"><a href="#cb38-127" aria-hidden="true" tabindex="-1"></a>convergence_times_df<span class="sc">$</span>Stage <span class="ot">&lt;-</span> <span class="fu">factor</span>(convergence_times_df<span class="sc">$</span>Stage, <span class="at">levels =</span> stage_names)</span>
<span id="cb38-128"><a href="#cb38-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-129"><a href="#cb38-129" aria-hidden="true" tabindex="-1"></a>subexpr <span class="ot">&lt;-</span> <span class="fu">bquote</span>(<span class="st">"El crecimiento anual de la población es "</span> <span class="sc">*</span> lambda <span class="sc">==</span> .(<span class="fu">round</span>(dominant_eigenvalue, <span class="dv">4</span>)))</span>
<span id="cb38-130"><a href="#cb38-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-131"><a href="#cb38-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-132"><a href="#cb38-132" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Crear el Trazado Usando ggplot2 ---</span></span>
<span id="cb38-133"><a href="#cb38-133" aria-hidden="true" tabindex="-1"></a>population_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb38-134"><a href="#cb38-134" aria-hidden="true" tabindex="-1"></a>  all_data_df,</span>
<span id="cb38-135"><a href="#cb38-135" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Time, <span class="at">y =</span> Proportion, <span class="at">color =</span> Stage)</span>
<span id="cb38-136"><a href="#cb38-136" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb38-137"><a href="#cb38-137" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb38-138"><a href="#cb38-138" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Añadir líneas horizontales para la distribución de etapa estable</span></span>
<span id="cb38-139"><a href="#cb38-139" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(</span>
<span id="cb38-140"><a href="#cb38-140" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> stable_stage_distribution_df,</span>
<span id="cb38-141"><a href="#cb38-141" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">yintercept =</span> Proportion, <span class="at">color =</span> Stage),</span>
<span id="cb38-142"><a href="#cb38-142" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb38-143"><a href="#cb38-143" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">0.8</span></span>
<span id="cb38-144"><a href="#cb38-144" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb38-145"><a href="#cb38-145" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Añadir líneas verticales para el tiempo de convergencia</span></span>
<span id="cb38-146"><a href="#cb38-146" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(</span>
<span id="cb38-147"><a href="#cb38-147" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> convergence_times_df,</span>
<span id="cb38-148"><a href="#cb38-148" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">xintercept =</span> Time, <span class="at">color =</span> Stage),</span>
<span id="cb38-149"><a href="#cb38-149" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">"dotted"</span>,</span>
<span id="cb38-150"><a href="#cb38-150" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">1.0</span></span>
<span id="cb38-151"><a href="#cb38-151" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb38-152"><a href="#cb38-152" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb38-153"><a href="#cb38-153" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Convergencia a la distribución estable "</span>,</span>
<span id="cb38-154"><a href="#cb38-154" aria-hidden="true" tabindex="-1"></a>  <span class="at">subtitle =</span> subexpr,</span>
<span id="cb38-155"><a href="#cb38-155" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="st">"Paso de Tiempo"</span>,</span>
<span id="cb38-156"><a href="#cb38-156" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="st">"Proporción de la Población"</span>,</span>
<span id="cb38-157"><a href="#cb38-157" aria-hidden="true" tabindex="-1"></a>  <span class="at">color =</span> <span class="st">"Etapa de Vida"</span></span>
<span id="cb38-158"><a href="#cb38-158" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb38-159"><a href="#cb38-159" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rlt_style_colour</span>() <span class="sc">+</span></span>
<span id="cb38-160"><a href="#cb38-160" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb38-161"><a href="#cb38-161" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb38-162"><a href="#cb38-162" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb38-163"><a href="#cb38-163" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb38-164"><a href="#cb38-164" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb38-165"><a href="#cb38-165" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb38-166"><a href="#cb38-166" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="fu">max</span>(all_data_df<span class="sc">$</span>Time))</span>
<span id="cb38-167"><a href="#cb38-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-168"><a href="#cb38-168" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir el trazado final</span></span>
<span id="cb38-169"><a href="#cb38-169" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(population_plot)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="110-Propriedades_files/figure-html/indice16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Estas propiedades estructurales permiten comprender el significado biológico de la tasa de crecimiento poblacional introducida en el capítulo sobre crecimiento poblacional.</p>
<div class="hidden-note">
<p>Revisión:</p>
<p>RLT 2025_06_02</p>
<p>RLT 2025-11-22</p>
</div>



<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-caswell2001matrix" class="csl-entry" role="listitem">
Caswell H. 2001. <em>Matrix <span>P</span>opulation <span>M</span>odels: Construction, analysis, and interpretation</em>. Sunderland, Massachusetts, USA: Sinauer Associates.
</div>
<div id="ref-crone2011plant" class="csl-entry" role="listitem">
Crone EE, Menges ES, Ellis MM, Bell T, Bierzychudek P, Ehrlén J, Kaye TN, Knight TM, Lesica P, Morris WF, others. 2011. How do plant ecologists use matrix population models? <em>Ecology Letters</em> 14:1-8.
</div>
<div id="ref-jiang2020life" class="csl-entry" role="listitem">
Jiang S, Jaggi H, Zuo W, Oli MK, Gaillard J-M, Tuljapurkar S. 2020. Life-history dynamics: damping time, demographic dispersion and generation time. <em>bioRxiv</em>:2020-12.
</div>
<div id="ref-mangalam2022ergodic" class="csl-entry" role="listitem">
Mangalam M, Kelty-Stephen DG. 2022. Ergodic descriptors of non-ergodic stochastic processes. <em>Journal of the Royal Society Interface</em> 19:20220095.
</div>
<div id="ref-stott2011framework" class="csl-entry" role="listitem">
Stott I, Townley S, Hodgson DJ. 2011. A framework for studying transient dynamics of population projection matrix models. <em>Ecology Letters</em> 14:959-970.
</div>
<div id="ref-tremblay2015stable" class="csl-entry" role="listitem">
Tremblay R, Raventos J, Ackerman J. 2015. When stable-stage equilibrium is unlikely: integrating transient population dynamics improves asymptotic methods. <em>Annals of Botany</em> 116:381-390. DOI: <a href="https://doi.org/10.1093/aob/mcv031">10.1093/aob/mcv031</a>.
</div>
<div id="ref-williams2011distance" class="csl-entry" role="listitem">
Williams JL, Ellis MM, Bricker MC, Brodie JF, Parsons EW. 2011. Distance to stable stage distribution in plant populations and implications for near-term population projections. <em>Journal of Ecology</em> 99:1171-1178.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/raymondltremblay\.github\.io\/Dinamica_Poblacional\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./109-Crecimiento_poblacional.html" class="pagination-link" aria-label="Crecimiento Poblacional">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Crecimiento Poblacional</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./111-Elasticidad.html" class="pagination-link" aria-label="Elasticidad y Sensibilidad">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Elasticidad y Sensibilidad</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/raymondltremblay/Dinamica_Poblacional/edit/main/110-Propriedades.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/raymondltremblay/Dinamica_Poblacional/issues/new" class="toc-action"><i class="bi empty"></i>Informar sobre problema</a></li></ul></div></div></div></footer></body></html>